### ISSUE TITLE
Make call URL part of an account.

### ISSUE THREAD

**Issue by sirinath** [vector-im/element-call#1003]
#### What would you like to do?

Have the call URL persisted.

#### Why would you like to do it?

Use the same room for a meeting.

#### How would you like to achieve it?

Make call function part of an account.

**Comment by robintown** [comment]
I believe your request is already covered by the 'recent calls' section shown on the home screen:

![Screenshot 2023-04-19 at 16-31-16 Element Call Home](https://user-images.githubusercontent.com/48614497/233193406-0b86c3eb-c5e3-4d01-b7f0-374e9ad57509.png)

**Comment by sirinath** [comment]
Any one can use a past URL. There is no security or control.
