### ISSUE TITLE
Jitsi Meet / Zoom Featue Parity

### ISSUE THREAD

**Issue by sirinath** [vector-im/element-call#1041]
#### What would you like to do?

When for online conferences and teaching.

#### Why would you like to do it?

Like to use a free and open source platform which uses open standards.

#### How would you like to achieve it?

By requesting this functionality be implemented.

### Have you considered any alternatives?

Jitsi Meet

### Additional context

Can you add:
- live rooms
- audio room

Functionality to to the Elemental App.

Which can be streamed to multiple other platforms, recorded and can be started even if the room is empty.

**Comment by dbkr** [comment]
These should each be tracked in their own issue, I think they both already have their own issues.

**Comment by sirinath** [comment]
> I think they both already have their own issues.

What are these issues?
