### ISSUE TITLE
Federation is broken

### ISSUE THREAD

**Issue by YourSandwich** [vector-im/element-call#1100]
### Steps to reproduce

1. Two users from two different matrix homeservers join one room on Element
2. Start Element Call meeting

#### What did you expect?
Everybody can talk to each other

#### What happened instead?
Just users from the same home server can hear each other.

#### Info
If both home servers are hosted under the same IP-Address and both users are connected to the same Router, it just works.

### Operating system

Linux, Windows

### Will you send logs?

Yes

**Comment by YourSandwich** [comment]
Tried to send Logs but got -> `Failed to send logs: Loading chunk 31 failed. (missing: vector://vector/webapp/bundles/6999163e8ea74ea5c36c/31.js)` even if trying to download them :(

**Comment by YourSandwich** [comment]
This issue is related to Element-web, Element-Desktop client, i was not sure where to create the issue.

**Comment by robintown** [comment]
This sounds like a classic case of one homeserver not having any STUN/TURN server set up. We wouldn't expect calls to work unless all homeservers involved have one - could you get both users to check their homeservers with https://test.voip.librepush.net/?

**Comment by YourSandwich** [comment]
Hi, thank you for your response, the STUN servers work and have been tested for about 2 years now with Elements direct Calls, this tester also shows a positive test.

But I thought that Element Call is using WebRTC and STUN is not needed any more?

In this case, I should check the Turn servers logs, I imagine. I hope it has nothing to with that we are both using already populated Matrix Servers.

**Comment by robintown** [comment]
Element Call does use WebRTC, yes, as do direct calls, and in both cases WebRTC is reliant on STUN and TURN to establish connections with peers.

**Comment by robintown** [comment]
Yes, we've successfully held calls across matrix.org + element.io, and even with some personal homeservers in the mix

**Comment by YourSandwich** [comment]
@robintown Thank you for your Time! 
Indeed, **it was the STUN** Server of my Partner.
He had Policy based VPN routing, wrongly configured on his router, what caused the STUN port to flicker.
