### ISSUE TITLE
Pass OpenID token to JWT service

### ISSUE THREAD

**Issue by fkwp** [vector-im/element-call#1149]
Use OIDC endpoint to verify homeserver/user exitsence (but not whether the user is in a given call) \[Note on OIDC endpoint. This one is handled by Synapse rather than mandating an OIDC auth provider\] Example given for embedded mode, but is similar with non-embedded.

* EC asks client for OIDC token ([https://github.com/matrix-org/matrix-widget-api/blob/master/src/interfaces/WidgetApiAction.ts\#L37](https://github.com/matrix-org/matrix-widget-api/blob/master/src/interfaces/WidgetApiAction.ts#L37))
* Client asks HS for OIDC token ([https://spec.matrix.org/v1.7/client-server-api/\#post\_matrixclientv3useruseridopenidrequest\_token](https://spec.matrix.org/v1.7/client-server-api/#post_matrixclientv3useruseridopenidrequest_token))
* HS returns token to client
* Client returns token to EC
* EC sends token to LK JWT service with JWT request
* JWT service contact the user's native homeserver with OIDC token ([https://spec.matrix.org/v1.7/server-server-api/\#openid](https://spec.matrix.org/v1.7/server-server-api/#openid))
* HS returns user info,JWT service verifies that the user really exists on that HS
* JWT service retruns JWT

Note the JWT Service also returns the SFU web socket URL

**Comment by davidegirardi** [comment]
I suggest to add a claim with the room membership in the OIDC token issued by the homeserver.

The flow would be:

1. A user tries to start/join a call
2. The client asks Synapse for an OIDC token for the call in that room
3. Synapse checks if the user is in the room (and maybe in the future if the PL allows the user to start/join a call) and then returns a token with the room membership in a claim
4. The client relays the token to the LiveKit JWT service
5. The service verifies the token signature and issues a JWT with the proper claims
6. The process continues till the user can join the call

**Comment by dbkr** [comment]
https://spec.matrix.org/v1.7/client-server-api/#openid is the token that we get from synapse - afaics it's really just an opaque bearer token and doesn't support claims.

**Comment by davidegirardi** [comment]
The spec says:
> OpenID token information. This response is nearly compatible with the response documented in the OpenID Connect 1.0 Specification with the only difference being the lack of an id_token. Instead, the Matrix homeserver’s name is provided.

Such type of response is a, or is nearly identical to, JWT. Can't we just add the claims we need to the payload of the token?

**Comment by dbkr** [comment]
The key phrase there being, "the lack of an id_token" - that's the JWT part. So, yes, extending this endpoint to also return a token would be one way to do it. I would assume the auth team have opinions on this though.
