### ISSUE TITLE
Ensure screenshares are brought into the visible space in freedom mode

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/element-call#1154]
Observed on the Monday sync so needs validating, but it seems as if screenshares can appear outside of the visible area of the screen?
It would make sense to:
- Treat the person screensharing as a speaker even if they haven't actually spoken - i.e. ensure they are promoted to the visible part of the screen if not already there.
- Start their screenshare next to their tile, making the connection between them clear and ensuring that the screenshare is also visible. 
- There is an edge case where the person sharing was on the far bottom right of the visible area of the screen, meaning they are already visible so won't be promoted, but if their screenshare is placed next to them it won't be visible. In this case, the speaker should be bumped up one slot so that both their camera and screenshare are visible.

Does this seem ok?

**Comment by robintown** [comment]
This behavior is generally something the big grid layout already tries to do, but it's inadequate at it, so treating this as a defect

**Comment by robintown** [comment]
https://github.com/element-hq/element-call/pull/2325
