### ISSUE TITLE
Consider positioning of tiles when expanded and reduced to minimise movement

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/element-call#1156]
Tiles can move around in confusing ways if I expand one and then shrink it down again. I know it might be difficult to achieve, but as I user I would expect that if I expand a tile and then contract it again, the layout will be exactly as it was before I expanded it. 
How are we currently deciding on tile positioning when expanding and contracting? Is there any way we can improve the model to make it feel more logical and consistent?

**Comment by robintown** [comment]
I have some ideas for how we can make the expand and shrink operations exact inverses of one another, so I do believe this is possible. (It involves running our "fill gaps" routine in reverse in a somewhat nuanced way.)
