### ISSUE TITLE
Display number of attendees in a call

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/element-call#1157]

**Comment by jakewb-b** [comment]
@rufuskahler would you be able to provide a design for this?

**Comment by rufuskahler** [comment]
@americanrefugee – We could reuse your room header [people count component](https://www.figma.com/file/wqgXVb7RVaIybfRsXdWEiL/Trust-%26-Decoration?type=design&node-id=990-64077&mode=design&t=DAAAJ6rpfs4vVKKw-0) for this:

**Comment by SimonBrandner** [comment]
> @americanrefugee – We could reuse your room header [people count component](https://www.figma.com/file/wqgXVb7RVaIybfRsXdWEiL/Trust-%26-Decoration?type=design&node-id=990-64077&mode=design&t=DAAAJ6rpfs4vVKKw-0) for this:

Sounds good, would you be able to put together an example of how exactly would this look and be positioned in Element Call?

**Comment by robintown** [comment]
We did this
