### ISSUE TITLE
Update T&Cs to new EULA on or shortly after 7th July

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/element-call#1168]
### Your use case

The current Terms and Conditions will be replaced with our new End User Licensing Agreement on 7th July 2023. On or as soon as possible after that date, could we:

- Replace the existing link with the new one, which will be on https://static.element.io/legal/online-EULA.pdf
- Update the text from `Terms and conditions` to `End User Licensing Agreement (EULA)`

**Comment by fkwp** [comment]
for now we just hardcode it and do not get the information from the homeserver

**Comment by fkwp** [comment]
1. Change all hyperlink text from Update the text from "Terms and conditions" to "End User Licensing Agreement (EULA)"
2. the destination link would be either coming from the homeserver (depends on SRE/EMS being fast enough) or https://static.element.io/legal/online-EULA.pdf

**Comment by jakewb-b** [comment]
See https://github.com/vector-im/sre-internal/issues/2670 for SRE ticket

**Comment by robintown** [comment]
Note that the homeserver doesn't tell us what kind of document it returns; in fact the URL is sent back to us in a field called `privacy_policy`. One option would be to include the name of the document in the config.json file, but the problem with this is that we can't easily localize the name this way.

Instead, we should ask Legal if there's some generic term like "Terms and conditions" (is this considered generic?) that would encompass any document that a homeserver admin might put here.

But until we get an answer on that, hard-coding the text to "End user license agreement" is fine as an intermediate solution.
