### ISSUE TITLE
Element Call embedded mode: Refactor the lobby view (Consider Element Web Settings -> Call presets)

### ISSUE THREAD

**Issue by fkwp** [vector-im/element-call#1178]
## Recap
In embedded mode we currently present prior to the actual call a lobby view allowing to select an audio and a video device, respectively. This lobby view "lives" in Element Web/Desktop/Mobile and the "only" purpose is to select the desired devices which are then handed over to the iFrame hosting the actual element call. Note the settings in "Element Web/Desktop/Mobile -> Settings -> Calls" are ignored so far.

## Refactoring 
Going forward we should use the settings from "Element Web/Desktop/Mobile -> Settings -> Calls" and optionally allow for a lobby page prior to the call.

**Comment by robintown** [comment]
Element Web no longer uses a custom lobby page.
