### ISSUE TITLE
Automatically mute users when joining a call where participant number is greater than 8

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/element-call#1202]
### Your use case

When users join an in-progress large call, we should automatically set them to muted to avoid disruption and background noise on large calls. 

The behaviour should be that when they hit the lobby screen, they are pre-set to muted, and ideally there is some explanatory text such as 'this call is already busy so we have automatically muted you'. However they can still choose to un-mute themselves at this point, all we are doing is setting the default state.

**Comment by dbkr** [comment]
Is it worth just doing this without a prompt to start with, then adding the prompt once we have design for it?

**Comment by robintown** [comment]
I'd say so. The contrast between the button's muted and unmuted states is pretty noticeable, and we also have the ['you are muted' warning](https://github.com/vector-im/element-call/issues/1205) in the pipeline to mitigate that concern.
