### ISSUE TITLE
Make it easier for a user to locate their own tile in large grid layout

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/element-call#1203]
### Your use case

Even if I am not speaking, I may want to find my own tile and bring it into the visible space so I can keep an eye on how I appear. On very large calls it might be difficult to locate myself, and if lots of people are speaking I may eventually get pushed back down out of the visible area. We should consider how to:

- Locate my own tile easily
- Bring my own tile into the visible area easily
- Keep my own tile in the visible area even if other users are bring 'promoted'

**Comment by robintown** [comment]
We now always keep your own tile in the very first position in the grid by default.

**Comment by robintown** [comment]
Actually, this is waiting on a PR to land

**Comment by robintown** [comment]
https://github.com/element-hq/element-call/pull/2325
