### ISSUE TITLE
Prioritise making users with cameras enabled visible over users with cameras muted

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/element-call#1210]
### Your use case

As a lot of users join a call, some with cameras on and some with cameras off, we end up with a grid that has a mix of video feeds and blank avatars, and lots of users with cameras on are way down at the bottom. There is no way to resolve this except individually bringing all video-on users to the top, one by one, which is painful. 

There are a few things we could consider - some or all of the below might work, but this needs some UX thought.

- As a user joins, if their camera is on they should be sorted to top-left, if their camera is off, they should sort to bottom-right. But this could still gradually become mixed again as users turn cameras on/off.
- When a user turns their camera off, should they then be moved to bottom-right?
- Likewiser, when a user turns their camera *on* should they be moved to top? Moving them right to the top might draw more attention to them than they would want, so maybe just move into the visible area as if they were a speaker.
- Another option would be a 'sort all visible users to the top' button that just does it all for me as a one-off.

**Comment by toger5** [comment]
I agree with the thought that we should not overexpose (pushing them to the top) ppl on unmuting the camera. 
I like putting ppl to the bottom on mute however.
It could be enough to implement:
 - on mute: move to bottom
 - on show: move next to last shown tile
 - on join muted: move to bottom
 - on join unmuted: move next to last shwon tile
 
This most likely wont be perfect in all scenarios but it should make it very comfortable to turn on the camera without the fear of beeing "featured" too agressivly and still result in most unmuted videos beeing in the upper secion.

I also really like the button option. But i feel like we might want to have a conversation about the general ux direction we want to go with:
 - all automatic
 - all maual with lots of tools
 - one view to rule them all / multiple views for each purpose
 - ...

**Comment by robintown** [comment]
https://github.com/element-hq/element-call/pull/2325
