### ISSUE TITLE
Share screen with system audio option missing

### ISSUE THREAD

**Issue by dillfrescott** [vector-im/element-call#1211]
### Steps to reproduce

1. Be on windows
2. Try to screenshare
3. No audio option

### Outcome

There is no screen share with audio option
### Operating system

Windows 11 Pro

### Browser information

Version 114.0.5735.199 (Official Build) (64-bit)

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
What browser are you using? Where are you expecting to see the option?

**Comment by dillfrescott** [comment]
I tried with Chrome and now Edge.

![Screenshot 2023-07-08 192725](https://github.com/vector-im/element-call/assets/56714680/7c3a43d1-d9ca-456e-a588-4a5c5cbad212)

It's supposed to be where the arrow is pointing

**Comment by SimonBrandner** [comment]
You should be able to see it in the `Tab` tab, Chromium doesn't support sharing audio of specific windows and screens

**Comment by dillfrescott** [comment]
It used to work fine on windows at least. And same browser
