### ISSUE TITLE
Add higher quality/resolution video feed layer

### ISSUE THREAD

**Issue by toger5** [vector-im/element-call#1214]
### Your use case

Curently the video is limited to 480p even if the network would allow for higher resolutions.
This is a good resolution for one person. For a camere setup which shows a whole group of ppl it becomes apperant, that one cannot see the detials of individual ppl.

### Additional context

It would be great to activate the 720p or 1080p resolution layer.

**Comment by SimonBrandner** [comment]
Is this just a client-side thing or is there a server component?

(I somehow heard someone talking about simulcast but wasn't sure what to make out of it)

**Comment by SimonBrandner** [comment]
From what I gather we can have 3 layers at most. One definitely needs to be 720p, I also imagine the second one will be 360p, so the question is whether we need the 1080p layer or we'd rather have 180p

**Comment by SimonBrandner** [comment]
We decided for 180p given the sizes and number of tiles we have by default

**Comment by paulvt** [comment]
This might require a new issue. But when using Element Call in Element Web for an 1-on-1 call, it uses a 180p resolution for a tile that is 1368×907 on my desktop. That is rather blurry!
I hope the simulcast options can be adjusted to only use for example 720p for tiles this big.

(Receiving the call on the other end on Element X on a phone 180p seems just fine indeed.)
