### ISSUE TITLE
Animation issue in spotlight view

### ISSUE THREAD

**Issue by toger5** [vector-im/element-call#1215]
### Steps to reproduce

If the reordering algorithm reorders the tiles on the right the spotlight tile gets teleported downwards by a little bit and afterwards animates back up to the top. Therefore resulting in occasional glitches.

### Will you send logs?

Yes

**Comment by toger5** [comment]
This code will use the large grid layout for the base logic. This will most likely fix animation issues with the spotlight view.
pls get in contact with @robintown before working on this.

**Comment by robintown** [comment]
https://github.com/element-hq/element-call/pull/2382
