### ISSUE TITLE
When joining the call audio gets muted even if it was enabled in the lobby

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-call#1221]

**Comment by toger5** [comment]
I have also observed this.
do you have any additional conditions that have to pass. (For me it sometimes works and sometimes doesnt)

**Comment by SimonBrandner** [comment]
For me it never works, so I am the ideal candidate for debugging this :p

**Comment by SimonBrandner** [comment]
So far, I think it has to do with it not handling you using the default device in a non-explicit way

**Comment by toger5** [comment]
It works for video?
Toggling the button multiple times does make no difference?

**Comment by SimonBrandner** [comment]
I am aware - it _is_  quite weird
