### ISSUE TITLE
Ending screen-sharing through Chrome doesn't work correctly

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-call#1228]

**Comment by SimonBrandner** [comment]
This seems to work on https://meet.livekit.io/

**Comment by SimonBrandner** [comment]
Turns out this was a regression in LK - we need to update the SDK

**Comment by daniel-abramov** [comment]
> Turns out this was a regression in LK - we need to update the SDK

Thanks for checking this @SimonBrandner!

Could you please link the issue/update from LiveKit? (sometimes helps for transparency to figure out what was broken and why 🙂 )

**Comment by SimonBrandner** [comment]
LiveKit PR: https://github.com/livekit/client-sdk-js/pull/768
