### ISSUE TITLE
Simplify tiling and display modes

### ISSUE THREAD

**Issue by rufuskahler** [vector-im/element-call#1236]

**Comment by rufuskahler** [comment]
See lightweight comp analysis: https://www.figma.com/file/uK10AtiHtrCsRu1Yz8JFYm/VoIP-Comp-Analysis?type=whiteboard&node-id=0-1&t=wlMZFlO8bb6KTCgR-0

- In any mode, users should not need to manually interact in order to view the latest active participant or screen-share.
- In any mode, users should be able to see there own tile (or manually hide or minimise this, if unwanted).
- In any mode, users should expect to interact with a tile in a consistent way.

**Comment by robintown** [comment]
We did this (https://github.com/element-hq/element-call/pull/2485)
