### ISSUE TITLE
Grey Tile Livekit (Fixable by switching from spotlight to Freedom)

### ISSUE THREAD

**Issue by toger5** [vector-im/element-call#1259]
### Steps to reproduce

1. Durign a call one of the other participant has a grey tile
2. This grey tile can be fixed by switching layouts (Spotlight -> Freedom -> Spotlight)

### Related regeshakes

Rageshake: https://github.com/matrix-org/matrix-video-chat-rageshakes/issues/2944

### Operating system

macOS, Firefox

### URL for webapp

call.element.io (livekit)

**Comment by robintown** [comment]
My hypothesis for why this is happening is that the LiveKit participant has some mutable fields that we're not observing properly in the video tile component.

**Comment by fkwp** [comment]
needs more data

**Comment by fkwp** [comment]
unable to repo

**Comment by fkwp** [comment]
likely connected to https://github.com/livekit/components-js/pull/620
