### ISSUE TITLE
E2EE: UX when trying to join an encrypted call

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#1283]
### Your use case

We need some UX for what happens when users try to join an encrypted call. By default this will be that they get garbled media, which could be okay as a first cut for technical users, but is likely to just look broken to most people. This will also need to tell the user they must use a different browser to join the call or ask the hosts to turn off e2ee if they are on a browser that doesn't support e2ee.

**Comment by SimonBrandner** [comment]
This can be closed now since all E2EE calls have no alias, so we can detect that we're joining one
