### ISSUE TITLE
Video and audio tabs of settings are empty outside a call

### ISSUE THREAD

**Issue by robintown** [vector-im/element-call#1289]
### Steps to reproduce

1. Start on the recent calls page
2. Click your profile picture
3. Open settings

#### What did you expect?

The audio and video tabs should show device dropdowns

#### What happened instead?

The audio and video tabs are empty, which looks broken

### Operating system

NixOS unstable

### Browser information

Firefox 115.0.0

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
/me suggests a quick fix here - hide the tabs when not in a call
