### ISSUE TITLE
Unmuted when UI shows that I am muted

### ISSUE THREAD

**Issue by germain-gg** [vector-im/element-call#1345]
### Steps to reproduce

1. Join a call
2. Press the "spacebar" for a split second

#### What did you expect?

To the muted as soon as the spacebar is released

#### What happened instead?

People DM'ed me saying that I was unmuted, even though the UI was showing that i was muted.

#### Extra context

Toggling the mute state actually made me go on mute and solved the issue.

I was wearing AirPods, and when i pressed the spacebar, it actually toggled the "mic mode" of the airpods

This can't be reproduced all the time but i added as much context as i could.

### Will you send logs?

No

**Comment by daniellekirkwood** [comment]
On the 'other side' I saw @germain-gg's icon as 'unmuted' and his background noise moved his tile to towards the top of the screen. Interesting that I saw as unmuted but Germain didn't have that state reflected in their own view.

**Comment by dbkr** [comment]
https://github.com/vector-im/element-call/pull/1421 might fix this although I could only repro the opposite case, ie. the mute button claimed I was unmuted when I was muted (the mute icon in my video feed still updated).
