### ISSUE TITLE
Act on device change callback and update internal array of media devices

### ISSUE THREAD

**Issue by fkwp** [vector-im/element-call#1383]
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/devicechange_event

**Comment by dbkr** [comment]
It actually looks like livekit's components should be doing this all for us, so really this will be going through every possible case of device-changing, eg:

 * Choose a device to use explicitly and remove the device you're using
 * Use the OS default and add a device so the OS's default changes
 * Use the OS default device & remove that device
 * Use a device explicitly and add a new device that becomes the default

...etc etc if there are any other cases we can think of. All of these should do whatever is the expected thing, or something sensible.

**Comment by dbkr** [comment]
Okay, it seems there is a specific bug where if you're using the default, then disconnect that device and reconnect it, it switches to a different device but doesn't switch back when you reconnect the first device, and the UI still shows it using the first one!

**Comment by dbkr** [comment]
This was fixed by https://github.com/vector-im/element-call/pull/1687
