### ISSUE TITLE
Glitches where tiles disappear briefly and re-animate in from bottom left

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#1415]
### Steps to reproduce

Frequently during calls, tiles disappear and then re-animate in from the bottom left for no obvious reason.
 * We notice it mostly in spotlight mode / screenshare
 * It appears correlated with people leaving the call, although this doesn't always trigger it and other things appear to trigger it too.

It's possible it may be fixed once we switch to the new grid layout, although we're not sure about this. It will at least be simpler to fix once we only have one tile layout method in the app.

### Will you send logs?

No

**Comment by robintown** [comment]
https://github.com/element-hq/element-call/pull/2382
