### ISSUE TITLE
Two people going to call.foo/foobar puts them in two different calls

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#1419]
### Steps to reproduce

On PR 1348 with the new SPA e2e stuff:

1. Alice goes to call.url/foobar
2. Bob navigates to the same URL

#### What did you expect?
Probably either them to end up in the same unencrypted call or for them to just get an error telling them that we've turned e2ee on and they need to update their URLs (although the latter would break everyone's calendar links).

#### What happened instead?
They both end up in different calls!

### Will you send logs?

No

**Comment by robintown** [comment]
From discussing in internal rooms: showing a 404 seems like the best solution currently available to us
