### ISSUE TITLE
Soft crash in big grid layout

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#1422]
### Steps to reproduce

 1. Join a meeting with enough people that the large-meeting view happens (multiple rows of people, in my case it was 2.5 filled rows)
 1. Double-click one of the tiles to enlarge it
 1. Drag the new large tile towards the last tile in the last row (or maybe to the empty space afterwards)

From the stack trace, it looks like we've managed to get an `undefined` in the cells list somehow.

#### What did you expect?
Tile to be repositioned

#### What happened instead?
Crersh

### Will you send logs?

Yes

**Comment by robintown** [comment]
https://github.com/element-hq/element-call/pull/2325
