### ISSUE TITLE
Audio for some members sometimes comes out of a different output device

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#1438]
### Steps to reproduce

Sometimes, audio for one participant will come out of a different audio device to the one that's selected and used for everyone else. A possible trigger may be someone joining later in the call? Also may be Firefox specific?

### Will you send logs?

No

**Comment by toger5** [comment]
There is hope that this is also caused by the same issue that causes https://github.com/vector-im/element-call/issues/1437
