### ISSUE TITLE
Contrast issue with login button

### ISSUE THREAD

**Issue by germain-gg** [vector-im/element-call#1542]
### Steps to reproduce

1. See screenshot

#### What happened instead?

![Screenshot 2023-09-20 at 10 10 08](https://github.com/vector-im/element-call/assets/769871/024e9226-c394-472e-a453-b479f0b3c572)

### Will you send logs?

No

**Comment by pixlwave** [comment]
I guess it depends on window size, it was more extreme for me:

<img width="1464" alt="Screenshot 2023-09-20 at 10 35 13 am" src="https://github.com/vector-im/element-call/assets/6060466/5955b5ab-7397-46af-8a32-4b9b8af9374e">

**Comment by robintown** [comment]
Fixed by https://github.com/element-hq/element-call/pull/2576
