### ISSUE TITLE
"Local volume" is not user-friendly language

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-call#1579]
### Your use case

![Screenshot from 2023-09-25 10-46-47](https://github.com/vector-im/element-call/assets/1342360/42ee59d2-49de-4f66-9c46-f05a9845d966)

I don't think my mom would understand what "Local volume" meant. Discord calls this setting "User Volume", which may be clearer?

![image](https://github.com/vector-im/element-call/assets/1342360/8214be6a-c070-42fd-a84c-5dfb44232f3a)

**Comment by robintown** [comment]
Nowadays we just let the slider and the icon speak for themselves
