### ISSUE TITLE
Dragging a tile by the avatar captures the avatar instead of the tile.

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-call#1580]
### Steps to reproduce

1. Join a call in grid mode.
2. Drag a user tile by their avatar (not a placeholder, an actual image).

#### What did you expect?
I can drag the tile around to move it.

#### What happened instead?
I ended up dragging the avatar as an image (and can drop it on my e.g. desktop).

https://github.com/vector-im/element-call/assets/6060466/018cac11-47a9-4ccc-8982-f00974c54d9f

### Operating system

macOS 13.6

### Browser information

Safari 16.6 (18615.3.12.11.2)

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by robintown** [comment]
https://github.com/element-hq/element-call/pull/2325
We removed the ability to drag-and-drop in the interest of foregrounding the most important content automatically
