### ISSUE TITLE
I am muted in the call but Safari is showing a red mic in the address bar.

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-call#1581]
### Steps to reproduce

1. I am part of a call and muted.

#### What did you expect?

No one can hear me, no indication in the OS that my mic is being used.

#### What happened instead?

I think people can hear my typing and clicking. Safari shows a red microphone in the address bar. The menu bar shows the orange dot next to the clock.

<img width="1118" alt="Screenshot 2023-09-25 at 10 51 46 am" src="https://github.com/vector-im/element-call/assets/6060466/4052bcc6-b53d-41b7-aa6e-2c6f152d089f">

Whether or not I'm properly muted, this makes me nervous and feel like I might be sending audio.

### Operating system

macOS 13.6

### Browser information

Safari 16.6 (18615.3.12.11.2)

### URL for webapp

call.element.io

### Will you send logs?

Yes

**Comment by dbkr** [comment]
This is intended, slightly unfortunately, as audio devices often can't open fast enough that you can unmute and speak immediately, plus it causes bluetooth headphones to switch modes and helps mobile browsers realise you really do want to stay in the call, etc. It's sucky that this means the icon has to be in the browser, but unfortunately that's the way it is.

If you were not actually muted, this is a separate and much more serious bug.

**Comment by robintown** [comment]
Closing as expected (and necessary) behavior
