### ISSUE TITLE
Add an icon to make the total user count clearer

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-call#1588]
#### What would you like to do?

In my opinion, it's not clear what the count at the top right of Element Call is. While it is next to user's avatars, it's still not entirely clear that that number represents the total count of all users in the call. Especially when the users represented don't have avatars:

![image](https://github.com/vector-im/element-call/assets/1342360/f184fe1c-201e-416c-b040-ce53dedb7eb6)

#### How would you like to achieve it?

I think just getting rid of the avatars and replacing them with a "user" icon may be clearer. Here is a mockup:

![image](https://github.com/vector-im/element-call/assets/1342360/a5f19132-62d3-44ac-aaa9-44a6e4510157)

### Have you considered any alternatives?

I did consider adding the icon to the existing layout, but was less pleased with it:

![total-people-render](https://github.com/vector-im/element-call/assets/1342360/cdfffff9-4adc-4463-9573-cc59d30d7e93)

Another alternative is to just add the word "total" after the number in the current design.

**Comment by anoadragon453** [comment]
Google Docs handles it with a `+XX` bubble (similar to what we do with read receipts in Element Call). But you can mouse over the +XX to see the total, so you don't need to do the math in your head.

![image](https://github.com/vector-im/element-call/assets/1342360/5593a4b6-34ef-45ad-bd98-c69d8998168a)

**Comment by nadonomy** [comment]
@kongo09 says: 

> [hot] - it's really difficult to understand what these icons are supposed to do. As many people don't have avatars, it looks very cryptic on most calls. Why don't we make it easy for the user and simply write "7 participants" here and if you click on that, you get a proper list

**Comment by nadonomy** [comment]
@americanrefugee exploring more, considering the logic for when we use avatar fills vs initialisms. Considering more the differences between the element room header & element call contexts.

**Comment by americanrefugee** [comment]
I decided to replace the facepile with a simple User icon. This solves a few issues:

- We can't implement the facepile at this time anyway
- People are confused when showing initials instead of avatars (e.g. "What does J A T mean???")
- When shown in a room header within Element apps, the facepile makes sense... but on a call, it's not apparent that these are just previews of people avatars
- Doing some backend magic to show only image avatars would introduce further complexity

So, here's what the new solution would look like:

![Type=Mobile-landscape](https://github.com/vector-im/element-call/assets/112560169/74cd75a5-d792-4c4d-8734-94222eef3862)


And here's the [header component](https://www.figma.com/file/fq7cTHPNHZX3ttFW1gBEnv/Compound-Element-Call-Components?type=design&node-id=45-22485&mode=design&t=YXfifnu6uPHaprv3-4) with the updated people counter

**Comment by kongo09** [comment]
Great solution, very clear! Also a natural link point for a participant list at a later stage.

In that context, what is the M standing for in the blue circle?

**Comment by anoadragon453** [comment]
> In that context, what is the M standing for in the blue circle?

@kongo09 The `M` is the first letter of the meeting name, "Meeting Title Goes Here".

If we want to question whether that makes sense as well, that should be taken to a new issue.

**Comment by anoadragon453** [comment]
Note that we appear to be using a separate "user" icon for Element video rooms:

![image](https://github.com/vector-im/element-call/assets/1342360/3cef87b0-efd4-43e2-87a4-3166ab197ac5)

See the entry in the room list.

**Comment by kongo09** [comment]
> Note that we appear to be using a separate "user" icon for Element video rooms:

Well spotted! Surely should be the same?

**Comment by kongo09** [comment]
> > In that context, what is the M standing for in the blue circle?
> 
> @kongo09 The `M` is the first letter of the meeting name, "Meeting Title Goes Here".
> 
> If we want to question whether that makes sense as well, that should be taken to a new issue.

Ah, got it. And it's the same as the room header in Element Web with the room names. I guess once that's understood and once appreciating that a call is a room, it makes sense, technically. From a user perspective, this is unexpected, as the mental model of a video call has nothing todo with a Matrix room. If the UX vision is, that this icon at some stage will be customizable for a meeting, then the link is actually quite nice. I won't open a new issue on this.

**Comment by americanrefugee** [comment]
Two things...

1. The icon you spotted in the room list is legacy (old). We will replace that People icon when we redesign the left panel.
2. The meeting avatar... The initialism would only apply to unique meetings. If a call is placed from a room, then the room avatar would show here. But again, let's discuss if it makes sense to show any avatar at all.
