### ISSUE TITLE
Layout shift from 12 to >12 people is horrible

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-call#1613]
### Steps to reproduce

1. Be on a 12 person call, in a nice wide 4*3 layout.  Double clicking on a user zooms them to almost full screen, while leaving all other users visible.
2. 13th person joins
3. Layout reforms into a very small grid of thumbnails, which don't use all available space vertically /or/ horizontally (with large amounts of dead space to the left & right, if viewed on a typical fullscreen 1920x1080 style resolution laptop screen). Double-clicking on a user zooms them slightly (3x wider and 2x higher than other thumbnails).

#### What did you expect?

Rather than a huge layout shift from 12 to 13 users, keep the same pattern going - e.g. use grid layout for everything.

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by nadonomy** [comment]
From discussion with @americanrefugee @fkwp: This should be solved when we move to a single grid engine.

**Comment by robintown** [comment]
https://github.com/element-hq/element-call/pull/2325
