### ISSUE TITLE
Mobile layout no longer provides spotlight/freeform mode, and you can't zoom any more.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-call#1614]
### Steps to reproduce

1. Open EC on iOS and join a call
2. Double-tap on a user to zoom so you can see them more clearly.  Nothing happens any more.
3. Try to switch to Spotlight mode so the active speaker is automatically zoome.  No more spotlight button either.

#### What did you expect?

Core features like being able to tap enlarge users or enabling spotlight mode should be available on mobile - particularly on mobile, in fact, where limited screen real estate makes them even more important.

#### What happened instead?

I had to ask what happened, and got told i needed to rotate my phone into landscape to switch to spotlight mode.  This is spectacularly undiscoverable, unergonomic, plus semantically broken, given spotlight mode is the ability to automatically zoom who's speaking, which is nothing to do with landscape orientation.

We have built a *really* unique animated layout engine with EX - superficially it's the one differentiator we have over hangouts or teams or whatever, and we should make the most of it rather than trying to hide it...

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by DoM1niC** [comment]
yes I agree and on 1:1 Calls the view from a Mobile Participent is zoomed and unclear, the preview is fine here...

**Comment by nadonomy** [comment]
Closing in favour of this issue we created while triaging: https://github.com/vector-im/element-call/issues/1631
