### ISSUE TITLE
Audio & video buttons are the wrong way around

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-call#1617]
### Steps to reproduce

1. Try to audio mute yourself
2. Discover that you're clicking the video mute button instead

#### What did you expect?

Jitsi, old EC, and many other apps put the most frequently used buttons furthest left in the toolbar.  So, audio mute comes before video mute in the toolbar

#### What happened instead?

The current design inverts the order, tripping up everyone who got used to the old order (and/or Jitsi).  It feels surprising given audio mute is much more common as people unmute to speak than video mute, which tends to be a binary thing per call.

### URL for webapp

call.element.io

### Will you send logs?

Yes

**Comment by robintown** [comment]
Fixed in https://github.com/vector-im/element-call/pull/1589
