### ISSUE TITLE
No version visible in UI

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-call#1623]
### Steps to reproduce

1. Fill out a bug report
2. Wonder what build of the app you are reporting a bug about
3. Wonder how often the app gets released
4. Fail to find any version number in settings or elsewhere

#### What did you expect?

the app to tell me what version/build and url it is

#### What happened instead?

No build info

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by nadonomy** [comment]
From discussion with @americanrefugee @fkwp: This is in Figma: https://www.figma.com/file/fq7cTHPNHZX3ttFW1gBEnv/Compound-Element-Call-Components?type=design&node-id=52%3A37937&mode=design&t=t1ezeyaql1YU1ZXp-1

Should be picked up when we implement the designs.

**Comment by Half-Shot** [comment]
This has been solved for a long time. Under Settings > More > Developer.
