### ISSUE TITLE
Iterate on how to scale up on large displays

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-call#1629]
### Your use case

- We currently have a max/fixed width
- How confident are we in it? Should we let users scale up to whatever monitor size they have?
- What are the tradeoffs/considerations?

**Comment by nadonomy** [comment]
From discussion with @americanrefugee @fkwp: We can allow the display to scale up infinitely, with fixed margins instead.

@americanrefugee to explore/pen the values.

**Comment by americanrefugee** [comment]
@nadonomy I would recommend a fixed margin of 96px on the left and right sides, and the content would scale to fit. This would feel proportional to the header height, which is 80px + 16px margin.

**Alternatively**, if we really want an "edge-to-edge" feel, then I would recommend a 16px margin.

**Comment by robintown** [comment]
Cool, let's try out the value of 96px and see how it feels in practice
