### ISSUE TITLE
Re-consider mobile responsive constraints

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-call#1631]
### Your use case

- We limited responsive controls on mobile, some users are asking for spotlight back.
- Discuss & reconsider.

**Comment by nadonomy** [comment]
Note to self - Internal screenshot of previous behaviour: blob:https://develop.element.io/1f1e2107-60e5-48f3-b8b6-79fbcfb314fa

**Comment by nadonomy** [comment]
> @ara4n: it would be a massive design thinko imo to require the user to rotate the phone to unlock basic features like "zoom in on who's talking"

From discussion with @americanrefugee @fkwp:

- We believe we've addressed this in the Figma specs: [https://www.figma.com/file/fq7cTHPNHZX3ttFW1gBEnv/Compound-Element-Call-Components?type=design&node-id=619%3A16807&mode=design&t=t1ezeyaql1YU1ZXp-1](https://www.figma.com/file/fq7cTHPNHZX3ttFW1gBEnv/Compound-Element-Call-Components?type=design&node-id=619%3A16807&mode=design&t=t1ezeyaql1YU1ZXp-1)
- @americanrefugee is adding more notes to Figma to expand on the specs.
- The minutiae will also be picked up in implementation with @robintown.

**Comment by nadonomy** [comment]
Related issue (closed in favour of this one): https://github.com/vector-im/element-call/issues/1614

**Comment by robintown** [comment]
https://github.com/element-hq/element-call/pull/2463
