### ISSUE TITLE
Noise suppression

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-call#1638]
#### What would you like to do?

Element Call should run clientside audio processing to suppress unwanted background noise (especially keyboard typing suppression)

#### Why would you like to do it?

I've been using Google Meet a lot recently, and its noise suppression is freakishly good - not just keyboard noise suppression, but also suppressing barking dogs, car crashes, grandfather clocks and more... but without any obvious acoustic artefacts.  We should do it too.

#### How would you like to achieve it?

https://github.com/jitsi/rnnoise-wasm perhaps?

### Have you considered any alternatives?

Locking everyone in anechoic chambers

### Additional context

It's very cool that we've got to this point :)

**Comment by ara4n** [comment]
oh, dup https://github.com/vector-im/element-call/issues/714

**Comment by itsCodeAlchemist** [comment]
@ara4n Why closing as "Completed" and not "Duplicate" ?
