### ISSUE TITLE
Being able to set the Element Call widget URL from the messenger apps (Element Web/Desktop/mobile X)

### ISSUE THREAD

**Issue by fkwp** [vector-im/element-call#1751]
This needs work in:
-  element call widget url builder rust side
-  element call widget url builder js-sdk / element web side
- another option is to use MDM profiles

**Comment by toger5** [comment]
done on android

**Comment by iam-jun** [comment]
Hi, is it done on Element Web?

**Comment by fkwp** [comment]
> Hi, is it done on Element Web?

https://github.com/element-hq/element-web/blob/develop/docs/config.md#voip--jitsi-calls paragraph 6
