### ISSUE TITLE
On firefox, m.call.members seem to be sent in duplicate

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-call#177]
e.g. $ADOOo8wVbGQf5K2wx70mWsasflJstFeBBQJHxFBF428 and $IyYkcdViHI5_AAP530RstTiBcNMwZC0-fxYq_GywuuA are identical state events in #jan-12th:robertlong.dev

**Comment by ara4n** [comment]
This seems to cause signalling problems as it triggers two restarts of the call signalling for the callers.

**Comment by robertlong** [comment]
Are we actually sending duplicates or are we observing a member that left previously and then joined?

In the inspector I'm using the `room.currentState.getStateEvents()` method to fetch the member state events: https://github.com/vector-im/matrix-video-chat/blob/main/src/room/GroupCallInspector.jsx#L305

So I think that could pick up both of them incorrectly.
