### ISSUE TITLE
Screen sharing views have no fullscreen button.

### ISSUE THREAD

**Issue by foxlet** [vector-im/element-call#179]
**Is your feature request related to a problem? Please describe.**
During a video call, when screen sharing a full desktop, it can become difficult to read what's being presented on-screen. There's no option or button to make a particular view fill the entire screen, and the focus mode while larger is still too small for ultra-wide or 4K streams.

**Describe the solution you'd like**
A button that appears when hovering over a video stream to *full screen* that particular view.

**Describe alternatives you've considered**
Using F11 makes the whole UI take full screen rather than a single video stream.

**Additional context**
This is already possible in Firefox by right-clicking on a video stream -> Full Screen, but it isn't exposed in Chrome.

**Comment by robertlong** [comment]
@jakewb-b @gaelledel @ara4n how would we like to handle this? Full screen for the whole app would be pretty simple. Or do we need a full screen for each feed as described which would also be pretty simple? Does spotlight mode handle this well enough or is there more that we could do to help make it better?

**Comment by jakewb-b** [comment]
@robertlong I do sort of agree that even in spotlight mode, screenshares can feel a little small. I often drag the browser over to my large monitor so that I can make the window bigger, but on a laptop screen it's not ideal.
I think Gaelle would need to take a look at this, but I'd probably favour a toggle that makes the screenshare feed full-screen within the app.

**Comment by youdontneedtoknow22** [comment]
I can't agree more.
When screen sharing, it's important on small screens to be able to watch the whole shared screen in order to see some details.

**Comment by gaelledel** [comment]
@SimonBrandner Here we go! https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/Element-Call?node-id=2401%3A64352
