### ISSUE TITLE
Element-Call widget buttons disapeard

### ISSUE THREAD

**Issue by YourSandwich** [vector-im/element-call#1853]
### Steps to reproduce

1. Enter Element Call room inside element-desktop-nightly

#### What did you expect?
I can see and press the screenshare or hangup button

#### What happened instead?
Call works but there are no buttons

### Will you send logs?

No

**Comment by YourSandwich** [comment]
This is probably the cause of this commit https://github.com/vector-im/element-call/commit/70f32feb5f481156ac386e5d9919bbeceb22de8b

**Comment by YourSandwich** [comment]
The timing when it happend is also very close

**Comment by toger5** [comment]
Thanks for the quick feedback. Its fixed now.
https://github.com/vector-im/element-call/pull/1854
