### ISSUE TITLE
Active speaker flickers several times per second, appearing and disappearing from the sidebar

### ISSUE THREAD

**Issue by reivilibre** [vector-im/element-call#1894]
### Steps to reproduce

During a screenshare, the layout splits with a main pane and the right pane with a list of video feeds.

For the purpose of this example, assume that there is a screenshare active and someone without a video (if that matters) talking.

### Outcome

The person talking keeps appearing and disappearing from the sidebar. This happens multiple times a second, which makes it quite distracting.

I think the display should be debounced so it does not update several times per second, e.g. maybe the active speaker should remain for several seconds, especially since they have not been pre-empted by other active speakers.

### Operating system

Linux

### Browser information

Firefox

### URL for webapp

call.element.io

### Will you send logs?

Yes

**Comment by robintown** [comment]
Fixed by https://github.com/vector-im/element-call/pull/1906
