### ISSUE TITLE
EC stuck on "waiting for other participants" view on EX iOS

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-call#1922]
### Steps to reproduce

1. Using EX on Android and iOS, sign in with different accounts (iOS is our test account `@audaciousaardvark:matrix.org`)
2. On iOS, go to a DM and click the video camera button top-right
-> See "Waiting for other participants…" screen on iOS
3. Look on Android, see that the room shows an ongoing call sometimes (camera icon changes to a "Join" button)
4. Click on "Join" on Android
5. On Android, see "Waiting for other participants…" screen
6. On Android, see your own video as if you're in the call
7. On iOS, still see "Waiting for other participants…" screen

#### What did you expect?
If I start the call on iOS, I quickly get to the point where I see at least my own video feed

#### What happened instead?
iOS is stuck on "Waiting for other participants…" screen

### Operating system

iOS latest

### Will you send logs?

Yes

**Comment by kittykat** [comment]
Note: submitting a rageshake from iOS triggered a request to submit logs from Android

**Comment by robintown** [comment]
This is because rooms created from iOS don't have the power levels set up to allow joining calls. https://github.com/matrix-org/matrix-rust-sdk/pull/2883 related

**Comment by toger5** [comment]
The newest nightly should contain a fix that greys out the call button in case the permissions are set so that the user cannot participate.
So it is transparent to everyone that the admin decided to not allow group calls in this room.
