### ISSUE TITLE
Modal dialogues immediately disappear when you're the only person in a call on Firefox

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-call#1986]
### Steps to reproduce

1. Create a new call in firefox
2. Join it
3. Try and invite somebody or change settings
4. The modal appears but vanishes immediately (this doesn't happen if you use these dialogues before joining the call)

### Operating system

Windows 10

### Browser information

Firefox 120.0.1 (64-bit)

### URL for webapp

https://call.element.io/

### Will you send logs?

No

**Comment by toger5** [comment]
This is a rendering bug in firefox. The z-ordering is broken for some rendering paths. We have managed to improve the sitation by disabling strict contained mode.

Can you retry this on call.element.dev?

**Comment by robintown** [comment]
Indeed this can be closed by https://github.com/vector-im/element-call/pull/1970, but I'll wait since Timo has asked for confirmation

**Comment by robintown** [comment]
Closing, presumed fixed by https://github.com/vector-im/element-call/pull/1970

**Comment by lampholder** [comment]
Can confirm I am no longer seeing this issue on call.element.dev
