### ISSUE TITLE
Three camera's listed instead of two (Samsung S23 Ultra)

### ISSUE THREAD

**Issue by rajil** [vector-im/element-call#2017]
### Steps to reproduce

1. Start a call using Element X android.
2. Change Video>Camera options

#### What did you expect?
Expect Front and Rear camera
#### What happened instead?
See three camera options
- camera2 1, facing front
- camera2 3, facing front
- camera2 2, facing back

![image](https://github.com/element-hq/element-call/assets/379266/315c37dc-e01e-43c9-abd7-4ab4b7b33ddf)

### Operating system

Android 14 (Samsung S23 Ultra)

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by robintown** [comment]
Hi, these camera options are provided by the operating system and we have little to no control over them. Often the reason for duplicated camera options on mobile is because your device presents options to use the same camera feed at a different aspect ratio or zoom level.
