### ISSUE TITLE
Doesn't work in firefox

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-call#2018]
### Steps to reproduce

After clicking "Join call", it gets stuck at "Waiting for other participants"

![image](https://github.com/element-hq/element-call/assets/1389908/f4a532df-028d-42d3-a919-743de144aaf1)

Eventually it times out and says "You were disconnected from the call"

#### What did you expect?

Working calls

#### What happened instead?

Non-working calls

### Operating system

Ubuntu 22.04

### Browser information

Firefox 121.0

### URL for webapp

call.element.io

### Will you send logs?

Yes

**Comment by richvdh** [comment]
ah, it seems better in call.element.dev

**Comment by fkwp** [comment]
@richvdh can you test again pls on call.element.io we now have a new release in the wild.

**Comment by richvdh** [comment]
yay it works!

**Comment by richvdh** [comment]
Apparently this has regressed?

**Comment by toger5** [comment]
With the exact same symptoms? "Waiting for participants..."
on .dev or .io?

**Comment by richvdh** [comment]
Yes. On call.element.io.

**Comment by fkwp** [comment]
> Apparently this has regressed?

we had to rollback to a version prior to the MVVM refactoring.

**Comment by Half-Shot** [comment]
This seems fixed now @fkwp?

**Comment by fkwp** [comment]
right
