### ISSUE TITLE
Consider replacing Jest with Vitest

### ISSUE THREAD

**Issue by robintown** [vector-im/element-call#2019]
If we're to be serious about thoroughly testing new code, it might be worthwhile to look into improving the developer experience around testing.

[Vitest](https://vitest.dev/), which we're using successfully in Compound Web, and I also quite enjoy having used in personal projects, is a drop-in replacement for Jest that integrates nicely with your Vite config, so that you don't have to spend as much time in the long run getting your testing environment to behave like your runtime environment. It also runs in "watch mode" by default, where it listens for file changes and immediately re-runs the exact tests that could be affected by those changes, which makes the feedback loop between coding and testing that much shorter.

If this sounds like a good idea, we should switch to it sooner rather than later, while we have not that many tests to convert.

**Comment by hereje** [comment]
I would like to work on this task!
