### ISSUE TITLE
Changing the audio output device is not working with Firefox

### ISSUE THREAD

**Issue by wolfito76** [vector-im/element-call#2022]
#### Steps to reproduce
Click on "Settings" and select the tab "Audio"
The option to change the output device is not shown. Microphone is showing and changing the microphone is working.
![Bildschirmfoto vom 2024-01-02 15-03-38](https://github.com/element-hq/element-call/assets/14106486/80744bdc-ae30-4fa9-80ce-4cee567c40f3)

#### What did you expect?
The option to change the device for audio output.

#### What happened instead?
It's just missing.

### Operating system

Ubuntu 22.04 LTS

### Browser information

Firefox 121.0

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by robintown** [comment]
Hi, the reason why this option is hidden is because Firefox had a bug with output devices which broke acoustic echo cancellation: https://bugzilla.mozilla.org/show_bug.cgi?id=1849108

This bug has been fixed in Firefox 123, so in a month or so we can look into turning this option back on.

**Comment by wolfito76** [comment]
I opened the issue before I saw the exception for firefox in the code, but there was no comment explaining why.
Thanks for the clarification.
