### ISSUE TITLE
Wording issue: `action.submit` dispplayed in Settings / Feedback dialog

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-call#2031]
### Steps to reproduce

<img width="519" alt="image" src="https://github.com/element-hq/element-call/assets/3940906/453ec0db-6063-402e-932b-e80550e21973">

### Outcome

See the screenshot

### Will you send logs?

No

**Comment by robintown** [comment]
Fixed by https://github.com/element-hq/element-call/pull/1951
