### ISSUE TITLE
Add a way to stop incoming video feed to save bandwidth

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-call#2032]
#### What would you like to do?

Be able to switch off incoming video stream to save bandwidth

#### Why would you like to do it?

Add an option per other user to stop incoming video stream, and/or a global setting to stop them all

#### How would you like to achieve it?

Add an option per other user to stop incoming video stream, and/or a global setting to stop them all

### Have you considered any alternatives?

Could also be automatically managed if bandwidth is low. (This is maybe already the case?)

### Additional context

Saving network bandwidth can also save money on a metered network.

**Comment by ara4n** [comment]
one hack for this is to open a new blank tab over the top of the one which EC is showing. this will stop EC from receiving any video.

**Comment by ara4n** [comment]
dup https://github.com/element-hq/element-call/issues/210
