### ISSUE TITLE
Client-side muting of specific users

### ISSUE THREAD

**Issue by dreamflasher** [vector-im/element-call#2050]
#### What would you like to do?
Muting specific users only for me

#### Why would you like to do it?
When two participants in a meeting are physically in the same room (different computers), they will hear the other person twice: once directly and once with a lag via BBB.

#### How would you like to achieve it?
Person B can decide to mute and unmute person A for themself. Person B will thus hear person A only directly "over air", not via BBB. Person C (at some other location) is still able to hear person A as before.

### Have you considered any alternatives?

None, unless the lag can be decreased to really small values for participants in a local network.

### Additional context

This feature exists in Jitsi and Discord, and is requested for BBB: https://github.com/bigbluebutton/bigbluebutton/issues/10643
I like the way it's done in Jitsi: You have a volume control per participant, which additionally solves volume difference issues

**Comment by robintown** [comment]
This is implemented as of Monday (https://github.com/element-hq/element-call/pull/1989), and will find its way into a release soon
