### ISSUE TITLE
Pressing the video mute button doesn't turn off the camera

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-call#209]
...which is scary and wastes power.

**Comment by SimonBrandner** [comment]
By doesn't turn of camera you mean the light next to your webcam?

**Comment by ara4n** [comment]
both the light & the camera device itself :)

**Comment by SimonBrandner** [comment]
Sorry, what I meant is: do you and the other side still see the video from the camera?

**Comment by ara4n** [comment]
The other side cannot see the video, but the camera is powered on and the green LED is on, which is scary.  I can repro every time i hit the video mute button.

**Comment by robintown** [comment]
This is probably also due to https://bugs.chromium.org/p/chromium/issues/detail?id=642785

**Comment by SimonBrandner** [comment]
> This is probably also due to [bugs.chromium.org/p/chromium/issues/detail?id=642785](https://bugs.chromium.org/p/chromium/issues/detail?id=642785)

That sounds like it only talks about the light - not the camera actually recording

**Comment by kegsay** [comment]
I don't think it's a browser bug, as Jitsi doesn't do this in the same browser/machine.

**Comment by gsouquet** [comment]
I just hit the same issue. It looks like the mic indicator on macOs is also shown when muted.

**Comment by robintown** [comment]
Per @kegsay's comment this needs re-investigation
