### ISSUE TITLE
[Feature Request] Push to Talk

### ISSUE THREAD

**Issue by YourSandwich** [vector-im/element-call#2169]
#### What Would You Like to Do?
Implement an option to activate the microphone via a button press.

#### Why Would You Like to Do This?
To offer a straightforward method for microphone usage as needed, avoiding the capture of unnecessary or unwanted sounds.

#### How Would You Like to Achieve This?
Introduce a keyboard shortcut for microphone activation.

### Have You Considered Any Alternatives?

Yes, a Pipewire command that connects and disconnects the microphone to element based on a key press. However, this method is exclusive to Linux systems with Pipewire installed and may not be accessible for average users.

### Additional Context

I am exploring options to transition away from Discord with my friends, for whom the Push to Talk feature is essential.

**Comment by fkwp** [comment]
Have you tried pressing:
-  `m` toggling mute state or 
- `SPACE` Push-to-talk

**Comment by YourSandwich** [comment]
O wow, I did not know that. Is this remappable?
Unfortunately, it does not work outside of focus.

**Comment by fkwp** [comment]
> Is this remappable?

at the moment they are not and we do not have it on the roadmap yet.

> Unfortunately, it does not work outside of focus.

Thats a limitation (or a security feature) of browsers. They are not allowed to catch all key events.

**Comment by YourSandwich** [comment]
Thank you for informing me. 
Regarding the Element application, I primarily use Element Call within Element. 
Could it be feasible to implement this for Electron-based clients?

**Comment by fkwp** [comment]
> Could it be feasible to implement this for Electron-based clients?

That seems feasible. However, it is currently not in our scope due to
- the immense effort needed to implement it in a sane way on all different platforms (Windows, Linux X11, Linux Wayland, macOS) which require different handling due to different security OS constraints
- Given the effort and its being more a power-power-power user feature its not at the top of our backlog (though PRs welcome :-)
