### ISSUE TITLE
Element Call cannot be verified by other client(s)

### ISSUE THREAD

**Issue by evasil** [vector-im/element-call#2227]
### Steps to reproduce

1. Where are you starting? What can you see?

Installed Element Call with Livekit backend. Video chat works ok.
My Matrix server does not allow registration so I have to login on my Element Call first.
Login works ok on Element Call.
However that login cannot be verified on any of my other Matrix clients (Element Web, Element Desktop, Element Android).

2. What do you click?
When logged in in Element Desktop (for example) I see popup about new login. In sessions list I also see unverified Element Call session with weird ID. ID doesn't have domain name, OS and browser/client, as all my other sessions. Just ID as eg. `z_ix7TMt` and IP address.
I click "Verify Session" inside of Element Desktop and see the banner: "To proceed, please accept the verification request on your other device."  and nothing happens.

3. More steps…
Inside of opened Element Call session in browser I tried to check dev panel.
I see following messages in browser dev console when I click "Verify Session" in Element Desktop:
```

received to-device m.key.verification.request from: @my_matrix_username:my_matrix_domain.tld id: undefined


Verification request O42jWrlKm4m7lJymR0GbooiRZsic4zgI: m.key.verification.request event with id:undefined, content:{"methods":["m.sas.v1","m.qr_code.show.v1","m.reciprocate.v1"],"transaction_id":"O42jWrlKm4m7lJymR0GbooiRZsic4zgI","from_device":"02Tx-Nq1","timestamp":1709095679842} deviceId:02Tx-Nq1, sender:@my_matrix_username:my_matrix_domain.tld, isSentByUs:false, isLiveEvent:true, isRemoteEcho:false, phase:1=>2, observeOnly:false=>false
```

Where: 
my_matrix_username: is my real matrix username
my_matrix_domain.tld: is my real matrix domain

#### What did you expect?
I expected to have an ability to verify Element Call login session.
#### What happened instead?
Really nothing. Element Call session cannot be verified.

### Operating system

Windows 10, Arch Linux

### Browser information

Firefox 122.0, Chrome 122.0.6261.71

### URL for webapp

call.my_matrix_domain.tld, Element Call latest version from Git.

### Will you send logs?

No

**Comment by robintown** [comment]
Running Element Call on a homeserver not dedicated to calling is not a use case we currently support, see this section of the README:

> Element Call requires a homeserver with registration enabled without any 3pid or token requirements, if you want it to be used by unregistered users. Furthermore, it is not recommended to use it with an existing homeserver where user accounts have joined normal rooms, as it may not be able to handle those yet and it may behave unreliably.
