### ISSUE TITLE
Synapse / Element to execute self-hosted Element call

### ISSUE THREAD

**Issue by alexander-potemkin** [vector-im/element-call#2228]
#### What would you like to do?

I would like to configure Synapse server / Element client to use the Element call hosted on my server, as opposed to the http://call.element.io one

#### Why would you like to do it?

To use self-hosted instance

#### How would you like to achieve it?

Some kind of config - on the server or on Element call, so that it will register itself on the server, if possible.

### Have you considered any alternatives?

Yes, but I can't see any, to be honest. Probably, I can somehow modify Element client behaviour, but it doesn't seem to be easy, as it will require forking and separate builds for all of the platforms.

### Additional context

I can configure jitsi server by using .well-known location. Probably I can somehow use the same kind of thing for Element call?

**Comment by t3chguy** [comment]
https://github.com/element-hq/element-web/blob/develop/docs/config.md `element_call` - if you want a server-wide config I suggest https://github.com/element-hq/element-meta/issues

**Comment by alexander-potemkin** [comment]
@t3chguy , thank you! I believe for Desktop & mobile apps, that means that I have to rebuild the clients from scratch?

**Comment by t3chguy** [comment]
I'm not sure about mobile, but for desktop Yes you would need to package it yourself unless there was a server side config added like for jitsi.
