### ISSUE TITLE
View Only Mode

### ISSUE THREAD

**Issue by karlabbott** [vector-im/element-call#223]
**Problem**
It is a fairly common format to have video conferences, like webinars or demos, in which the participants join simply to listen to the presenter and not react/interact via video/voice. Given our limitation currently of ~8 users, this could be an interesting early win.

**Describe the solution you'd like**
I'd like to see a way to join an Element call in "View Only Mode", something like:

https://elementcallurl/matthewscooldemo/viewonly

that would enable me to join the call, but would not initiate video/audio sharing. This would enable me to still watch the contents of the call, but I wouldn't be transmitting anything. Further, the application in this mode would not have the ability to initiate video/audio sharing.

**Describe alternatives you've considered**
None at this time.

**Additional context**
The experience should be similar to going to a youtube live where you just get a stream of video but don't send one back. If you combined this feature with #213 you would have a really nice setup where you could do a Matrix room with Element call in a maximized widget and of course the room chat out to the side.

**Comment by heyakyra** [comment]
I think this is covered by (or a subtask of) #174

**Comment by karlabbott** [comment]
@heyakyra You are right -- this is covered as a subtask of #174 Closing this one to consolidate.

**Comment by heyakyra** [comment]
I actually think it is reasonable to keep this open as a subtask, I was just mentioning the relation @karlabbott
