### ISSUE TITLE
Can't start a call on self-hosted instance

### ISSUE THREAD

**Issue by alexander-potemkin** [vector-im/element-call#2235]
### Steps to reproduce

1. Where are you starting? What can you see?

I'm starting a call and pass a link to the second person. Once he joins, number of participants is '2', but the system still says it's 'Waiting for other participants...'

2. What do you click?

Start call, confirm video, invite - copy link.
Open the link on another end.

3. More steps…

Installed Livekit, dedicated Synapse instance (with no registration) and rolled-out static web app.

#### What did you expect?

Call to start, like it is on call.element.io

#### What happened instead?

My video disappears, system says waiting for another participant to join.

No specific logs in console (same errors, as on call.element.io).

### Operating system

Ubuntu 22.04 (both server and one participant) & MacOS Sonoma

### Browser information

Latest Brave, Safari

### Will you send logs?

No

**Comment by alexander-potemkin** [comment]
Happy to provide logs, if I can send them manually.

**Comment by toger5** [comment]
Logs would be good. There can be numerous things causing this. Since the participant count goes up chances are high its sth with the SFU connection. Failing or getting rejected or ...

**Comment by alexander-potemkin** [comment]
@toger5 , sure - how do I get the logs? I've seen an option to send them via web-interface, but I would like to see them on my own before sending to you, if that's fine?

**Comment by toger5** [comment]
Oh. That makes sense.
Dont know of a really easy way. what you can do however is:
```
await global.mx_rage_store.flush();
await global.mx_rage_store.consume();
```
the global.mx_rage_store will contain the logs and this is what we add to the rageshake when sending it.
https://github.com/vector-im/element-call/blob/204d24c3008a6cd1d33564127e5e96d0d2c80473/src/settings/rageshake.ts#L522-L545

The rest of the data for the rageshake (this is what we call the feedback report) can be found here:
https://github.com/vector-im/element-call/blob/204d24c3008a6cd1d33564127e5e96d0d2c80473/src/settings/submit-rageshake.ts#L64
You can see what data it will obtain.

**Comment by alexander-potemkin** [comment]
@toger5 , thank you very much for the details and please, apologies for the delay in getting back!

I've been distracted but now got back on track, started it all from scratch and it seems to be working fine. I'm preserving the instructions you kindly shared though.

All the best luck to you and to whatever you dedicate yourself!
