### ISSUE TITLE
Remove entries from previous call list

### ISSUE THREAD

**Issue by dreamflasher** [vector-im/element-call#2243]
#### What would you like to do?
https://call.element.io/ shows a long list of previous calls, and I'd like to delete specific entries from that list.

#### Why would you like to do it?
The list of previous rooms is fantastic for recurring calls that use the same room, but outdated rooms clutter the list over time.

#### How would you like to achieve it?
Have a delete button on each room entry.

### Have you considered any alternatives?

Make a list of all rooms I still need, delete cookies/storage and reopen all still needed

**Comment by spaetz** [comment]
I know this is not what you want, but you can log into the call.ems account using any other client (e.g. fluffychat or whatever) and leave the rooms that you don't want to see anymore...

**Comment by dreamflasher** [comment]
That's great to know! When I created my calls a couple of months ago Element generated a username for me, and I don't have a password. But apparently now you can create accounts with passwords, so I can move my calls to that new account. Is there anything like rights management with the rooms? Will I have different rights because I joined them with an account that didn't create them?

**Comment by toger5** [comment]
We are currenlty steering into the direction to make element call compatible with element web.
All more advanced user features (recent calls, leaving rooms with calls ...) would be available there.
In general the idea is to not bloat the EC app and anyone (or any group) seeking for more features and organizsation tools are invited to work with the embedded calling in element web.
We need to be careful to not make EC a full client (adding chat, editing recent rooms, renmaing rooms, organzing calls in spaces ... at some point we are building a full matrix client.) Some of those features will come but only features that are of value for the occasional call guest. Someone who uses matrix calls on a regular basis will always be better of using a proper client with call support like EW.
Removing recents is still suddle enought to make sense though. A contribution for this would be very welcome.

If you just want a workaround that is possible today: You can leave rooms by logging into EW using you Element Call matrix account and manage the rooms there.

**Comment by dreamflasher** [comment]
Happy to hear that you are planning to integrate EC with EW. I created an account in order to manage rooms by logging into EW. Unfortunately, I can't login to EW with my EC credentials (homeserver call.ems.host) – "Signing in" keeps spinning and that's it. Shall I create a new issue that this login does not work?

[EDIT] It does not work with EW, but it does work with Cinny.
