### ISSUE TITLE
Volume control button does not work in full-screen

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-call#2277]
### Steps to reproduce

1. Fullscreen a feed
2. Click volume control button
3. Nothing happens

#### What did you expect?

The volume control dialog to appear

#### What happened instead?

Nothing

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by robintown** [comment]
This is fixed on call.element.dev as we've now put the volume control in a context menu, call.element.io is just stuck behind by a couple of releases currently

**Comment by SimonBrandner** [comment]
Good to hear!
