### ISSUE TITLE
AV1 codev error on the latest versions of Edge, Brave and Chrome

### ISSUE THREAD

**Issue by Cocam123** [vector-im/element-call#2329]
### Steps to reproduce

On the latest version of the Edge, Brave, Chrome browsers (and probably others), an error occurs when we want to start a screen share

### Operating system

Windows

### Browser information

Microsoft Edge Version 124.0.2478.51 / Brave Version 1.65.114 Chromium: 124.0.6367.60 / Chrome Version 124.0.6367.61

### URL for webapp

call.element.io

### Will you send logs?

Yes

**Comment by bblacher** [comment]
https://github.com/element-hq/element-call/pull/2327

**Comment by robintown** [comment]
This compatibility issue is already fixed on the `livekit` branch (hosted at https://call.element.dev), and we are working to get a release out soon that includes this change

**Comment by Cocam123** [comment]
alr thanks you robin :D
