### ISSUE TITLE
"How was this call quality?" surveys at end of calls

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-call#236]
An easy way to get more confidence on launching this would be to show a "please rate this call" at the end of every call, and phone it back somewhere (posthog?)

**Comment by jakewb-b** [comment]
Design is here https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/Element-Call?type=design&node-id=3078-66101&t=JjnXTMZH0BLaMyhl-0

**Comment by toger5** [comment]
How do we want the behaviour to be if the user still has not setup an account. In this case we show a prompt to ask for creating an account.



Do we want to combine those two screens? or should they come one after the other. If we show them consecutively, in which order?

**Comment by toger5** [comment]
Cool. Thanks jake, that sounds sane.
