### ISSUE TITLE
Screen sharing audio doesn't work

### ISSUE THREAD

**Issue by ElTioRata** [vector-im/element-call#2398]
At least for me (and a friend), we tried screen sharing with audio but I didn't work both on sharing the whole screen and only sharing a window.

#### What did you expect?
Audio screen sharing to work.
#### What happened instead?
It didn't work.

### Operating system

Windows 10

### Browser information

Firefox 126.0.1 (I also tried Edge but same result)

### Will you send logs?

Yes

**Comment by fkwp** [comment]
Hi, screen sharing with audio is sadly only supported from Chrome and only for Chrome-tabs.

**Comment by ElTioRata** [comment]
@fkwp It is supported on the desktop app? I tried with a friend and I couldn't hear his audio.

**Comment by fkwp** [comment]
It's not low hanging since Chrome only allows audio sharing for browser tabs to my knowledge. It's also a security sensitive area to capture the system audio output. I guess, it requires a sane way to request OS system audio output API prior to get this into WebRTC/Browsers.
