### ISSUE TITLE
Ringing does not stop in the room even when caller hangs up

### ISSUE THREAD

**Issue by rajil** [vector-im/element-call#2421]
### Steps to reproduce

Have a room with 3 users A, B and C using EXA

1. User A click 'Call' button in the room
2.  Ringing appears on devices B and C
3.  Caller A hangs up the phone

#### What did you expect?
Ringing on devices B and C should stop, and call should be torn down.
#### What happened instead?
Ringing continues on devices B and C for another ~12 seconds. If B and C join the call they find an empty room (since A is already hung up).

### Will you send logs?

No

**Comment by robintown** [comment]
@stefanceriu/@jmartinesp Could you please transfer this issue to the Element X Android repository? I don't have triage rights there.

**Comment by jmartinesp** [comment]
There is already https://github.com/element-hq/element-x-android/issues/3014 so I think we can close this one as a duplicate.
