### ISSUE TITLE
Magically mute without user input (automatically) after starting the call

### ISSUE THREAD

**Issue by toger5** [vector-im/element-call#2464]
### Steps to reproduce

For some users the call mutes automatically approx 5s into the call without user input.

**Comment by robintown** [comment]
Right, I'm pretty certain that this is just the "mute when there are >8 participants" behavior triggering as we were talking about this morning @toger5. It seems this line of code was designed to run no matter whether you're in the lobby or the actual call:

https://github.com/element-hq/element-call/blob/82a56c8204cf3c8cfd27babe2785210e640fc35f/src/room/GroupCallView.tsx#L90
