### ISSUE TITLE
element-desktop integration

### ISSUE THREAD

**Issue by OrionRandD** [vector-im/element-call#247]
I have a element-desktop client to access matrix in my GNU/Linux Debian that I installed with:

sudo apt install element-desktop

Will I be able to access element-call inside element-desktop?
https://github.com/vector-im/element-desktop

Also, I use jitsi-electron desktop application for video conferences in my Linux.
Any chance to have a like DA for element-call as well?
https://github.com/jitsi/jitsi-meet-electron
Thx a lot for the project...

**Comment by SimonBrandner** [comment]
This is planned but not possible atm

**Comment by OrionRandD** [comment]
> This is planned but not possible atm

Great! At least it is planned...
