### ISSUE TITLE
call.element.io offline/down

### ISSUE THREAD

**Issue by mxwmnn** [vector-im/element-call#2517]
### Steps to reproduce

520 error cloudflare Host reach failed 

#### What did you expect?
Getting the page
#### What happened instead?
520 error

### Operating system

all

### Browser information

all

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by fkwp** [comment]
@mxwmnn any chance that you can handover some network logs from your web browser? (web browser -> dev tools -> network tab)

**Comment by robintown** [comment]
Seems to be running fine now :)
