### ISSUE TITLE
Spatial audio

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-call#252]
We need it for TR anyway; it'd be lovely for EC to help distinguishing speakers.

**Comment by niklaskorz** [comment]
Repeating what I already posted at https://github.com/bigbluebutton/bigbluebutton/issues/13712:

The [web audio API supports spatial audio out of the box](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Web_audio_spatialization_basics). There is also https://resonance-audio.github.io/resonance-audio/ by Google which adds reverb effects on top. If you want to compare them yourself, see https://github.com/niklaskorz/audio3d and https://niklaskorz.github.io/audio3d/.
