### ISSUE TITLE
View a single participant fullscreen

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-call#261]
**Is your feature request related to a problem? Please describe.**
I was trying call.element.io and someone shared their screen. The biggest I could make their video is by using spotlight to make it big and display the other participants on the right side? Due to the fixed video aspect ratio and the other feeds taking a fixed with, the actual area used by the screenshare was only like 70% of my screen space.

**Describe the solution you'd like**
I would like to "fullscreen" one single video feed, either hiding everyone else completely

**Describe alternatives you've considered**
or put them as very small overlays on top, while still filling the screen, as jitsi, zoom, ... do

**Comment by dbkr** [comment]
Related to (maybe dup of) https://github.com/vector-im/element-call/issues/277, https://github.com/vector-im/element-call/issues/179 and https://github.com/vector-im/element-call/issues/273

**Comment by dbkr** [comment]
OK, it's a dup of https://github.com/vector-im/element-call/issues/179
