### ISSUE TITLE
Docker Compose support

### ISSUE THREAD

**Issue by fwsGonzo** [vector-im/element-call#2613]
#### What would you like to do?

I would like to run docker compose up, with a simple YAML configuration

#### Why would you like to do it?

To avoid manual typing and tutorial hell

**Comment by fkwp** [comment]
Hi @fwsGonzo thx for reaching out. You could use https://github.com/element-hq/element-call/blob/livekit/backend-docker-compose.yml as starting point.

**Comment by CoherentThought** [comment]
I'm also interested in using this project, but it would be very helpful if there was an official, working docker compose which is not just for development. Looks very promising so far

**Comment by alexander-potemkin** [comment]
> Hi @fwsGonzo thx for reaching out. You could use https://github.com/element-hq/element-call/blob/livekit/backend-docker-compose.yml as starting point.

It feels like that docker-compose.yaml indeed requires quite some work: it misses Synapse server, no livekit credentials, no front-end configuration via environments.

It would be of much use it you could share the parts you use in production, whenever possible!

**Comment by WawaCallMePepe** [comment]
can this be deployed at any point? wasted a few days looking through browser console and docker logs to find out, that dev configuration is poorly documented and confusing
