### ISSUE TITLE
participant disconnection (close tab, alt + f4)

### ISSUE THREAD

**Issue by Sxoo** [vector-im/element-call#266]
**Describe the bug**
It seems that participant disconnection from a call with a chrome incognito tab does not work after closing the tab. The participant which disconnected with a closed tab hangs in the meeting until he gets booted with a timeout. 

**To Reproduce**
1. create a call with chrome. 
2. join the call with an incognito tab on chrome. 
3. close the incognito tab.
4. the incognito user is left hanging in the meet with a frozen video frame for 30 seconds~.

**Expected behavior**
the person, who closed an incognito tab should get booted out with a small delay, or there should be some indication that the connection is lost. 

**Desktop (please complete the following information):**
 - OS: MacOS BigSur 11.3.1
 - Browser Chrome
 - Version Version 99.0.4844.51 (Official Build) (arm64)

**Additional context**
could provide a video if needed, but the issue seems easy to reproduce. 
it most likely happens because ant alt + f4 doesn't provide a hangup, but acts more like a connection lost, which you handle that way. nevertheless I believe some kind of indication should be visible to the user which is still participating in the call.

**Comment by robintown** [comment]
We can use the `keepAlive` capability of the `fetch` API to make this more reliable

**Comment by SimonBrandner** [comment]
We should now have this
