### ISSUE TITLE
Failed ED to ED call. 

### ISSUE THREAD

**Issue by neilisfragile** [vector-im/element-call#2664]
### Steps to reproduce

Try to start a call in a 1:1 room, 

#### What did you expect?
have a video call via Element Desktop
#### What happened instead?
I, the caller can see the callee, the callee cannot see or hear me. 

Rageshake details 
https://github.com/element-hq/element-web-rageshakes/issues/27307

### Will you send logs?

Yes

**Comment by fkwp** [comment]
might be fixed by https://github.com/livekit/client-sdk-js/pull/1272

(currently mitigated by rolling call.element.dev to v0.6.6)

**Comment by toger5** [comment]
Closing this as it is tracked int he PR @fkwp linked: https://github.com/livekit/client-sdk-js/pull/1272
