### ISSUE TITLE
Youtube video does not work while on Element Call - Chrome Browser

### ISSUE THREAD

**Issue by tmissoni** [vector-im/element-call#267]
On the same browser, Chrome in this case, if I have an Element Call active on a tab, Youtube videos does not work.
If I open Youtube on another browser, the video starts without any problem.

**To Reproduce**
Start an Element Call in a tab
Open another tab
go to Youtube.com
start any video

**Expected behavior**
Video should start as well

**Screenshots**
<img width="978" alt="Screenshot 2022-03-09 at 18 27 13" src="https://user-images.githubusercontent.com/63042679/157497384-647df2d2-9841-4459-a5f5-39918f245a42.png">

**Desktop (please complete the following information):**
 - OS: OSX 12.2.1 M1
 - Chrome
 - Version 98.0.4758.109 (Official Build) (arm64)

**Comment by dbkr** [comment]
I juts reproduced this, although I can't really work out what caused it. Somehow we must be crashing chrome's audio renderer...

**Comment by robintown** [comment]
@tmissoni Do you have spatial audio enabled?

**Comment by dbkr** [comment]
I think this predates spatial audio

**Comment by turt2live** [comment]
(it predates spatial audio)

**Comment by tmissoni** [comment]
> @tmissoni Do you have spatial audio enabled?

@robintown nope
