### ISSUE TITLE
Can't share screen in Element Desktop

### ISSUE THREAD

**Issue by visubesy** [vector-im/element-call#2683]
### Steps to reproduce

1. Go to a video room with Element Desktop (lab feature "video calls" is enabled).
2. There is no button to share the desktop, unlike Element Web. Camera and audio work.

#### What did you expect?
I expected that Element Desktop would show a button to share the desktop.
#### What happened instead?
There is no button: 
![grafik](https://github.com/user-attachments/assets/9273bc48-3b9d-4edb-83e2-afbb095df3a5)

### Operating system

Windows 10

### Browser information

Client: Element Desktop 1.11.81 (Krypto Version: Rust SDK 0.7.2 (7a21514), Vodozemac 0.7.0)

### URL for webapp

Server: matrix-synapse (1.95.1-1~bpo12+1, Debian bookworm-backports)

### Will you send logs?

No

**Comment by fkwp** [comment]
this looks like the Jitsi Integration rather than Element Call.

**Comment by visubesy** [comment]
> this looks like the Jitsi Integration rather than Element Call.

You were right. I thought that Element Call had been used in my video room, not Jitsi.

I had to use the *nightly* version of Element Desktop, activate *Element call video rooms* in addition to *Video rooms* there, and create a *new* video room to actually see Element Call instead of Jitsi. Then the share button was available:
![screenshot](https://github.com/user-attachments/assets/77fff533-746b-4ec8-aa98-6fa13c6c42fc)

Sorry for the circumstances.
