### ISSUE TITLE
Call latency can get *really* high when bandwidth is a bit constrained

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-call#269]
Since starting to use call.element.io in the wild in general, i've had several instances where someone (typically me) has been on somewhat bad connectivity and constrained bandwidth.  The media quality drops as you'd expect from the other side, but then media ends up being at least 5-10 seconds delayed.  Unclear if it's due to be my uplinks being delayed, or due to the downlinks of the other parties being delayed, but in practice it makes it unusable.

I wonder if we should be explicitly measuring latency somehow and use that as a metric into aggressively dialling down bitrate.

Related to #250

**Comment by ptman** [comment]
Bufferbloat?

**Comment by robintown** [comment]
Closing since this issue was about the full-mesh mode of operation. We still see this happening on occasion with LiveKit though, and are tracking that in a new issue here: https://github.com/vector-im/element-call/issues/1442
