### ISSUE TITLE
Provide an option to play a sound when a screenshare is started/stopped

### ISSUE THREAD

**Issue by bblacher** [vector-im/element-call#2696]
#### What would you like to do?
I'd like to have element call play a sound when someone shares their screen. There could also be a sound when microphone mute is toggled. Discord and Jitsi have these sounds (at least some of them)

#### Why would you like to do it?
I like having the extra information that there is something relevant to look at. (Sometimes you have element call minimized)

#### How would you like to achieve it?
There could be a setting/config option to enable this behavior.

**Comment by Half-Shot** [comment]
With https://github.com/element-hq/element-call/pull/2794 landing this is now trivial, if we can figure out a sound. I'll see if I can do something when I am next near my keyboard.
