### ISSUE TITLE
Allow user volume slider to be set to 200%

### ISSUE THREAD

**Issue by bblacher** [vector-im/element-call#2697]
#### What would you like to do?
I'd like to be able to set other user's volumes past 100%

#### Why would you like to do it?
Sometimes call members are way too quiet, the only option is to ask these people to boost their microphone volume. ([This is another issue right now because automatic gain can't be disabled if Element Call is used within Element Desktop](https://github.com/element-hq/element-call/issues/248))

#### How would you like to achieve it?
The volume slider should go to 150% or 200%

### Have you considered any alternatives?

Asking people to boost their volume is a temporary fix until automatic gain control turns them down again. Boosting desktop volume and decreasing all other participants would also be possible but very inconvenient.

**Comment by Destinyg133** [comment]
Would be cool feature

**Comment by Twi1ightSparkle** [comment]
See also https://github.com/element-hq/element-call/issues/1349

**Comment by robintown** [comment]
Duplicate of https://github.com/element-hq/element-call/issues/2697

**Comment by bblacher** [comment]
What? You linked this issue as its own duplicate :)
