### ISSUE TITLE
Ability to rapidly switch camera between front & back

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-call#2712]
#### What would you like to do?

When embedded in EX, it's super common to want to switch between front & back camera.  Right now you have to fiddle around with device settings, whereas it should be a single 🔄 button of some kind.

### Additional context

See also https://github.com/element-hq/element-call/issues/2703 to some extent

**Comment by fkwp** [comment]
already merged https://github.com/element-hq/element-call/pull/2694 and deployed to call.element.dev
