### ISSUE TITLE
Starting video call with camera on mute still has camera LED on

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-call#276]
I started a video call, deliberately with camera off, and was then freaked out by the camera LED staring at me throughout the call.

**Comment by SimonBrandner** [comment]
Duplicate of https://github.com/vector-im/element-call/issues/195 which is caused by [bugs.chromium.org/p/chromium/issues/detail?id=642785](https://bugs.chromium.org/p/chromium/issues/detail?id=642785)

**Comment by robintown** [comment]
Closing as such
