### ISSUE TITLE
Clicking "Mute for me" should show a visible icon on the tile.

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-call#2773]
### Steps to reproduce

1. Have a call with someone.
2. Open the context menu and click "Mute for me"

#### What did you expect?

The tile would show a local mute icon (not the remote mute icon)

#### What happened instead?

No icon is present, and some users get confused when they have muted someone and forgot..

### Operating system

Arch Linux

### Browser information

Firefox

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by fkwp** [comment]
you mean different from https://github.com/element-hq/element-call/pull/2772

**Comment by Half-Shot** [comment]
Oh, lol.
