### ISSUE TITLE
No feedback on mobile that a reaction is sending

### ISSUE THREAD

**Issue by toger5** [vector-im/element-call#2788]
## Current
On desktop i get a custom hover cursor so that i know the reaction is still sending and i cannot send another one.
On mobile this is not the case and I am confused why I cannot click the button again.
## Expected
Setting the buttons to disabled state while the event is sending would be nice.

**Comment by Half-Shot** [comment]
Covered by https://github.com/element-hq/element-call/pull/2751/commits/171b5a522e05b0d9a7df8dec3f01641659022a3b
