### ISSUE TITLE
1:1 Calls on Widescreen stretch the video tile

### ISSUE THREAD

**Issue by robertlong** [vector-im/element-call#281]
**Describe the bug**

**To Reproduce**
1. Open Element Call maximized on a wide screen device
2. Join a call by yourself
3. Observe the super wide cropped tile

**Comment by moritzdietz** [comment]
Is this a duplicate of #240?

**Comment by SimonBrandner** [comment]
> Is this a duplicate of #240?

Yep, looks like it
