### ISSUE TITLE
Embedded call shows on top of Element Desktop upgrade prompt

### ISSUE THREAD

**Issue by hughns** [vector-im/element-call#2837]
### Steps to reproduce

1. Be using Element Desktop
2. ED has an updated version available (this is obviously more common on the Nightly channel)
3. ED prompts to update the client
4. Join an embedded Element Call

#### What did you expect?

The update prompt to show on top of the call.

#### What happened instead?

The prompt was shown underneath the call.

![image](https://github.com/user-attachments/assets/e351d862-0cf1-4075-a74b-a822a39be572)

### Will you send logs?

No

**Comment by bblacher** [comment]
element-web issue: 
https://github.com/element-hq/element-web/issues/27167

This also applies to Download, New Login, etc. prompts.

**Comment by robintown** [comment]
See the Element Web issue
