### ISSUE TITLE
Raising hand should move tile into view

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-call#2843]
### Steps to reproduce

If a user raises their hand, and their tile is off the screen, it should be moved into view.

#### What did you expect?

I haven't checked explicitly, but i'm assuming that particularly if you are in spotlight mode, if someone raises their hand and they're off the bottom of the list, they won't get moved into view.

#### What happened instead?

I suspect folks were raising hands on my call and i couldn't see them.

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by Half-Shot** [comment]
Yep, on our wishlist. It needs #2701 to land first so we can directly mutate the state of the tiles based on Matrix events. Currently this isn't possible.
