### ISSUE TITLE
Emoji reactions cause phantom pushes on EX

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-call#2844]
### Steps to reproduce

1. Do a EW+EC -> EW+EC call
2. Send some emoji reactions to the other person.
3. Their EX buzzes with a blank notif every time they receive an emoji reaction in the call

#### What did you expect?

Emoji reactions sent on video calls shouldn't result in mobile push notifications firing.

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by Half-Shot** [comment]
This sounds like an EX bug where it's trying to surface unrenderable timeline events as notifications? If EX can't handle rooms sending custom events, that rather screws up a lot of use cases.

**Comment by Half-Shot** [comment]
Having considered this further in standup, this is likely that EX notifies on every encrypted message. I assume because we make the invalid assumption that every encrypted message should be noisy (as it might be a message?).

**Comment by robintown** [comment]
I've had to reopen this manually on the Element X repo since I don't have permission to transfer: https://github.com/element-hq/element-x-ios/issues/3632
