### ISSUE TITLE
Expose a seperate volume slider for join/leave sounds

### ISSUE THREAD

**Issue by bblacher** [vector-im/element-call#2861]
#### What would you like to do?
I'd like to change the volume of the join/leave event separately from the reaction sound volume.

#### Why would you like to do it?
Because I want to increase the volume of the join/leave sound without becoming deaf when someone plays the rock reaction.

#### How would you like to achieve it?
With the help of a second volume slider.

**Comment by toger5** [comment]
The Element call team discussed this in a meeting and we try to not get too fine grained with the settings.
We will revisit the volumes in general and potentially adjust the defaults to be better balanced.

The reason for this decision is that Matrix is an open standard and the beauty of it is, that we do not need a one client fits all user solution.

So this really sounds like there is the need for something like a "schildi Element Call" or a more customizable calling client.

EC as a project tries to solve this: "Make an as simple as possible MatrixRtc call client".
