### ISSUE TITLE
Asking for webcam/microphone permissions while they are already granted

### ISSUE THREAD

**Issue by ghost** [vector-im/element-call#287]
**Describe the bug**
I am told that "Webcam/microphone permissions needed to join the call." even when the website has these permissions

**To Reproduce**
1. Go to element call
2. Join a room
3. See error

**Expected behavior**
It should let me join the call

**Video**

https://user-images.githubusercontent.com/70704875/161140219-506b68e1-ee17-4914-9c31-71e21162f9ca.mov

**Desktop (please complete the following information):**
 - OS: `Linux (openSUSE Tumbleweed)`
 - Browser `Firefox`
 - Version `98.0.2`

**Comment by dbkr** [comment]
I can't reproduce this - it's presumably hitting an error at some point: we'd need to find out what's going on (I don't think our bug report function will currently give us enough info).

**Comment by somerandomguy24** [comment]
From my testing, I think I have found a way to reproduce this.
1) open firefox
2) type `about:config` into the url bar
3) set `privacy.resistFingerprinting` to true
4) go to element call, create a call, and see the issue

I would like to point out even with `privacy.resistFingerprinting` set to true, other call sites such as google meet behave properly

**Comment by robintown** [comment]
@somerandomguy24 That appears to be a separate issue, which is tracked at https://github.com/vector-im/element-call/issues/396

**Comment by somerandomguy24** [comment]
I am the person who opened the issue originally, just deleted my account and made a tmp one to solve some issues, and this is how I got the same issue I had, so unless you noticed something different in the logs, I think this and https://github.com/vector-im/element-call/issues/396 are the same.

**Comment by somerandomguy24** [comment]
![image](https://user-images.githubusercontent.com/109069892/189498121-d271e52d-8ca6-43f6-b615-ff65a7da7246.png)
This is with more or less the same firefox config I had before since I didn't reinstall, but now I am on v104.

**Comment by somerandomguy24** [comment]
![image](https://user-images.githubusercontent.com/109069892/189498161-5eea6490-6d06-4ec4-bdb3-de80728044a9.png)

**Comment by somerandomguy24** [comment]
Nvm, it is different as there is no error spam and it does not even request to use the microphone and camera, but they probably have the same root problem.

**Comment by somerandomguy24** [comment]
On a fresh profile, it works fine, but when I enable RFP and refresh, I get my problem.

**Comment by robintown** [comment]
Hi @somerandomguy24, we just shipped some fixes that are supposed to make Element Call work better with resistFingerprinting enabled, though still none of us have been able to reproduce your exact issue here. When you get the chance, perhaps you could try the latest [call.element.io](https://call.element.io) version to see if it has changed anything?

**Comment by robintown** [comment]
Okay, good to hear!
