### ISSUE TITLE
Massive performance improvement with 1. Talking token | 2. Bittorrent mesh | 3. Decentralized muxing

### ISSUE THREAD

**Issue by hoergen** [vector-im/element-call#289]
This feature request is only related to the performance issues,when doing lager video conferences and the currently need to send 1:1 video and audio streams.

### 1. Talking Token
I always wondered why in video conferences all video and audio (even if muted) has to be send continuously to everybody.  Why isn't there already a feature, where you configure a conference call, that only the person who is actually speaking gets a "talking token" so that you can reduce the video streams that a sent from everybody to only 1 stream. 

All participants that are mute or not talking are visible by the rest of all participants as a freeze frame and their clients are not sending a video/audio stream as long they are not talking.

### 2. Bittorrent Mesh
There is bittorrent for a really long time to show that distributed management of sending and receiving data reduces the load of one sender. Peertube is showing that in a really great way. So the first participant in a call (Host) will be the tracker for all participants and will manage all the connections with following chains (like a pyramid scheme/network)

```
                                                                  +-- P3 sharing with (P9/10/11)   ......
     +-Participant 1 - sharing with p 3/4/5 -+--   P4   sharing with (P12/P13/P14)   ......
                                                                 +-- P5 sharing with (P15/P16/P17) ......
Host --
     + Participant 2 - sharing with 6/7/8

```

### 3. Decentralized muxing
A step further would be that todays computers and smartphones have such a cpu power so every client could mux 2 video/audio streams to reduce the bandwith even more

This would open up huge video conferencing without any central muxing video/audio service and using the decentralized power of all connected devices that are anyway up and running.

Use that power.

**Comment by dbkr** [comment]
Thanks for the feedback. The issue board is intended to be for specific, single, actionable tasks and defects though, so I'm going to close this as it's not really in the right place.
