### ISSUE TITLE
Feature Request: Volume Slider :)

### ISSUE THREAD

**Issue by DillFrescott** [vector-im/element-call#293]
**Is your feature request related to a problem? Please describe.**
Yes! I can't adjust the volume of people in the call. Sometimes one person is a lot louder or quieter than another.

**Describe the solution you'd like**
Just a simple volume slider to adjust participant volume.

**Describe alternatives you've considered**
Having the other person adjust their mic volume, but usually this isn't very feasable.

**Additional context**
n/a

**Comment by DashieTM** [comment]
If there will be screensharing audio, then it would also be useful to individually set the volume of these audio streams, as they are often not balanced in volume.

**Comment by DillFrescott** [comment]
I think this has been added right?

**Comment by robintown** [comment]
Yep!
