### ISSUE TITLE
PTT - Disable video in PTT mode

### ISSUE THREAD

**Issue by fkwp** [vector-im/element-call#295]
- As a user who joins a VoIP call in radio mode
- My camera is off and I cannot turn it on
- So that I can only speak using the ‘radio-style’ PTT experience

**Comment by dbkr** [comment]
At the js-sdk layer this is free since we already have voice mode. At the UI layer it will need the button to turn on video removed, not display videos etc.

**Comment by dbkr** [comment]
This is now done!
