### ISSUE TITLE
PTT - UX and switching PTT on

### ISSUE THREAD

**Issue by fkwp** [vector-im/element-call#300]
- As a room admin
- I can decide whether my VoIP call will be in ‘radio’ mode or conference mode
- So that the right functions can be applied, and so that regular VoIP calls do not have the undesirable PTT experience

**Notes**
- Regular VoIP calls can still have the more straightforward ‘push-to-unmute’, but all of the functionality of this PRD, i.e. only one user being able to speak at once, beeps on pressing transmit, default-to-mute, etc must only be on a call that is deliberately set as a ‘radio’ call.
- This setting should be somewhat buried as 90% of users will not be interested in it or understand it. 
- It should also be persistent - once a given VoIP room is set into radio mode it stays in that mode until an admin changes it.

**Comment by dbkr** [comment]
This is now the case (although not with final UI yet).

**Comment by dbkr** [comment]
We have designs for this now: https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/Element-Call?node-id=2196%3A63242
