### ISSUE TITLE
InCallView.jsx right-hand side of 'in' should be an object, got undefined

### ISSUE THREAD

**Issue by rosbeef** [vector-im/element-call#302]
**Describe the bug**
page not loading

**To Reproduce**
1. run with --host option
2. Go to '192.168.0.xxx:3001'
3. See error in the console

**Expected behavior**
loading page

**Screenshots**
black webpage

log : 

```
Uncaught TypeError: right-hand side of 'in' should be an object, got undefined
    <anonymous> InCallView.jsx:23
```

message : 

```
    InnerModuleEvaluation self-hosted:2331
    InnerModuleEvaluation self-hosted:2331
    InnerModuleEvaluation self-hosted:2331
    InnerModuleEvaluation self-hosted:2331
    InnerModuleEvaluation self-hosted:2331
    evaluation self-hosted:2292
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Browser :firefox 99.0 64b or chromium 100.0.4896.127 (Official Build) snap (64-bit)
 - Version  vite v2.7.13

**Comment by dbkr** [comment]
I'm not seeing this problem - could you paste the *exact* commands you're running?
