### ISSUE TITLE
Convert JavaScript to TypeScript in Element Call

### ISSUE THREAD

**Issue by fkwp** [vector-im/element-call#330]
Convert src/**/*.jsx to .tsx

**Comment by fkwp** [comment]
https://github.com/vector-im/element-call/pull/491

**Comment by fkwp** [comment]
https://github.com/vector-im/element-call/pull/487

**Comment by fkwp** [comment]
https://github.com/vector-im/element-call/pull/511

**Comment by robintown** [comment]
This is now done
