### ISSUE TITLE
PTT - bad-network conditions currently break PTT semantics partly

### ISSUE THREAD

**Issue by fkwp** [vector-im/element-call#331]
Under certain (bad network) circumstances the reliability of the WebRTC or the home-sever network connection might differ significantly which triggers unwanted behavior in the PTT logic.

**Comment by fkwp** [comment]
https://github.com/matrix-org/matrix-js-sdk/pull/2401

**Comment by dbkr** [comment]
Going to close this now as we've done the planned work on it. If we find that we need more in practice, we can open another issue.
