### ISSUE TITLE
PTT – Camera shouldn't be called "Webcam" on mobile devices

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-call#344]
**Describe the bug**

The term "webcam" is common on desktop and laptop devices but feels a bit out of place when using Element Call on a mobile device.

**Expected behavior**

Maybe use "camera" instead?

**Screenshots**

![webcam](https://user-images.githubusercontent.com/1137962/169379810-8b4c75f3-e20c-46e7-a289-d84b95d8d3a1.png)

**Additional context**

See also #324.

**Comment by compgeniuses** [comment]
Why not change the webcam name to something Generic, like "CAM" or "Device CAM"
