### ISSUE TITLE
 VU animation in PTT mode

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#355]
**Is your feature request related to a problem? Please describe.**
VU meter style animations in push to talk mode would give more visual indication of when the other side is speaking

**Comment by ara4n** [comment]
My quick suggestion to unblock this:

> honestly i think the easiest bet there would be to effectively mask the circular VU meter rings with a circle whose diameter corresponds to the the amplitude, as a first cut
> and then can be reused for the mic control for normal EC
> and Gaelle can then finesse as needed
> (i don't necessarily literally mean a CSS or SVG mask btw, but faking the opacity/diameter of the various rings to give the same effect)

**Comment by ara4n** [comment]
https://github.com/matrix-org/matrix-js-sdk/blob/706b4d605481a66d02e24d15f34cd7e0dbebef4b/src/webrtc/callFeed.ts#L243 looks like it will make this very easy
