### ISSUE TITLE
Video room connects for some users but not others

### ISSUE THREAD

**Issue by JimKillock** [vector-im/element-call#383]
**Describe the bug**

Using an Element Call room, https://call.element.io/jim-appointments I connected and appeared to be in the room; two others joined, but apparently were in a different room.

I will report if this problem reoccurs, and also try reusing this room to see if it is room specific.

**Comment by ara4n** [comment]
yup, very likely that this is a stale cache of Beta 1. we really should add a warning in Beta 2 if it starts receiving unencrypted calls.
