### ISSUE TITLE
Joining a call and not closing the tab results in strange audio driver behaviour

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-call#388]
For entirely unknown reasons, when either participating or previously participating in a call and leaving the tab open other audio issues start to happen. The ones I've noticed are:

1. YouTube fails to load videos (looks to be a timeout issue)
2. Jitsi calls can play sound effects, but you cannot hear other people

Closing the element-call tab fixes both issues.

It feels like element-call is getting an exclusive lock on the audio output device which prevents other things (like youtube's player and Jitsi's webrtc stuff) from getting a similar playback lock. If this is the case, element-call could probably get a less dramatic lock and still work.

**Steps to reproduce**:
1. Participate in an Element Call call.
2. Leave the call, but don't close the tab.
3. In another tab, play a youtube video.
4. Video fails to load.
5. Close Element Call tab.
6. Refresh youtube tab
7. Video plays fine.

**Device**: Windows 10, Chrome

It is unclear if the audio issues would persist across browsers, or if it's localized to the browser that ran Element Call.

**Comment by robintown** [comment]
https://github.com/vector-im/element-call/issues/267 related

**Comment by robintown** [comment]
Closing as such
