### ISSUE TITLE
MediaHandler goes into an infinite loop in Firefox with resistFingerprinting

### ISSUE THREAD

**Issue by opusforlife2** [vector-im/element-call#396]
**Describe the bug**

When the web app tries to start the camera and mic after being granted permissions on Firefox, they keep getting toggled on and off repeatedly forever, until I manually stop the process, by reloading the page, or in some other way.

The Web Console is spammed with this error log repeatedly until manual intervention:

`Uncaught (in promise) DOMException: The fetching process for the media resource was aborted by the user agent at the user's request.`

I use Arkenfox's user.js, so it's possible that some hardened preference is causing this. For example, CORS is being denied to Matrix Sentry, though I'm assuming that's just analytics, and irrelevant to the functioning of the web app.

If that is the case, could you specify what needs to be changed? For the record, Jitsi and other web apps work fine with my setup.

**To Reproduce**

1. Enter a username and room name and join call (doesn't matter which type).
2. Grant camera and/or mic permissions when asked.
3. Error occurs. Open Web Console to see error message spam.

**Expected behavior**

The camera and/or mic to work and for the call to go ahead.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Firefox 100

**Comment by opusforlife2** [comment]
Correcting a small inaccuracy: I actually can start the call, which means I get to the active call interface. But the problem remains that the camera/mic toggling continues.

Also, Firefox shows 2 icons in the taskbar indicating the camera and mic are being used. Several pairs of these icons appear one after the other, then the entire set disappears, and then they start appearing again, continuing the cycle.

**Comment by opusforlife2** [comment]
Likely a duplicate of #287, as I too have RFP turned on as part of Arkenfox, and the video in that issue shows the same console error I've mentioned above.

**Comment by opusforlife2** [comment]
Any workaround for this, other than using Chromium-based browsers?

**Comment by robintown** [comment]
From what I can tell, there appears to be infinite recursion between MediaHandler and useMediaHandler with resistFingerprinting enabled, with useMediaHandler repeatedly calling `setMediaInputs`, and that repeatedly emitting a `LocalStreamsChanged` event.

https://bugzilla.mozilla.org/show_bug.cgi?id=1711619 indicates that the resistFingerprinting.exemptedDomains option is still in development, so for now the only workaround would be to disable resistFingerprinting altogether.

**Comment by opusforlife2** [comment]
Thanks for the info.

> For the record, Jitsi and other web apps work fine with my setup.

Is Element Call using some feature that these other apps don't need? I just tested Jitsi again with the exact same setup, and everything works fine.

**Comment by robintown** [comment]
Nope, this is simply a bug on our end
