### ISSUE TITLE
Scrolling people list didn't scroll my video

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-call#398]
**Describe the bug**

When I was in a call and my colleague was sharing his screen, then I scrolled the list of people, they all scrolled except me, who stayed in the same place.

**To Reproduce**
1. Start a call with several other people - enough to make the list of people scroll when someone is sharing
2. Ask someone to share the screen
3. Scroll the right-hand side (e.g. using the mouse wheel)
4. Notice that your video is fixed and everyone else scrolls

**Expected behavior**
Everyone scrolls together the same way.

**Screenshots**
![rec-2022-06-13_15 15 27](https://user-images.githubusercontent.com/76812/173374370-2d16b3db-b3f3-4d06-9316-1df4b3492de1.gif)

**Desktop (please complete the following information):**
 - OS: Ubunut 21.10
 - Browser Firefox
 - Version 100.0

**Comment by andybalaam** [comment]
I rageshaked but am not sure how to find it to link to. I think the description was "Scrolling people list didn't scroll my video"

**Comment by babolivier** [comment]
I've observed this today as well.
