### ISSUE TITLE
PTT mode sends RTP even when muted

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-call#402]
Even when muted, we're sending 50Hz of silent audio packets to every other participant in the room.  This obviously doesn't scale, and screws up PTT performance, and destroys battery life.

**Comment by fkwp** [comment]
https://webrtc.ventures/2022/01/dtx-audio-optimization/

**Comment by robintown** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/2482
