### ISSUE TITLE
RTCPeerConnection leak

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#411]
**Describe the bug**
We appear to be leaking RTCPeerConnections between calls

**To Reproduce**
1. Enter a group call
2. Leave
3. Maybe repeat above steps a few times to make it more obvious
4. Take heap snapshot
5. Observe RTCPeerConnection(s) still referenced
<img width="1233" alt="Screenshot 2022-06-17 at 11 45 36" src="https://user-images.githubusercontent.com/986903/174283718-d5cedc97-f19a-4f5c-9f68-b2eef9558471.png">

**Comment by robintown** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/2484
