### ISSUE TITLE
Side-by-Side view / Larger Participant Video

### ISSUE THREAD

**Issue by sosnik** [vector-im/element-call#414]
**Is your feature request related to a problem? Please describe.**
Currently, your own video preview is relegated to a small corner of your screen. There is no way to enlarge it or change where it is. You can rearrange other participants, but not yourself.  This behaviour is okay for a meeting or presentation, but inconvenient for anything else (for instance, recording an interview / podcast).

**Describe the solution you'd like**
Simple: allow the user's own video to be the same size as any other participant instead of just a tiny preview (of course, this should be toggleable).

Bonus: allow some videos to be larger than others, for instance 1 4x4 video, 2 1x2s and 4 1x1 videos. 

**Describe alternatives you've considered**

Skype's Side by Side view. Streamyard and the million other online streaming platforms. 

**Additional context**

So far I've only tested this with 2 participants. I'm not sure if my desired behaviour exists with 3+ participants, but, ideally, it should work with two people as well. The primary usecase is things like interviews, podcasts and similar.

**Comment by robintown** [comment]
Closing since this feature exists
