### ISSUE TITLE
Starting screen sharing on Leg-A breaks Leg-B's session completely (black screen)

### ISSUE THREAD

**Issue by fkwp** [vector-im/element-call#421]
**Describe the bug**
Just had a call (Firefox -> Firefox) using element call. Screensharing was completely broken. When Leg-A started screen sharing my session broke completely (black screen); not recovering after he stopped screen sharing...

**Comment by dbkr** [comment]
Provisionally, it looks like we get this error:

> 2022-07-19T09:00:47.544Z E AudioContext.createMediaStreamSource: No audio tracks in MediaStream (InvalidStateError | 11)

and then the app tries to display an error screen which then, itself, causes a hook error.

I haven't yet found a way to repro the first error though.

**Comment by dbkr** [comment]
Ah, of course this is if someone starts a screenshare and you have spatial audio enabled.
