### ISSUE TITLE
PTT: Audio capture broken on mobile safari

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#423]
**Describe the bug**
It seems sometimes mobile safari can fail at some point in the audio capture pipeline such that media doesn't get through to the other side and the VU meter rings don't animate on the local capture side.

No media detail available at present.

**Comment by robintown** [comment]
I presume this was another one of the symptoms fixed by https://github.com/matrix-org/matrix-js-sdk/pull/2484
