### ISSUE TITLE
remoteSDPStreamMetadata can be missing in pushRemoteFeed

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#426]
**Describe the bug**
On trying to reproduce another bug, I got an exception where one side failed to place a call to the other because it threw an exception in `pushRemoteFeed` due to there being no entry for the stream in this.remoteSDPStreamMetadata.

<img width="572" alt="Screenshot 2022-06-29 at 14 45 04" src="https://user-images.githubusercontent.com/986903/176451959-e2edaf59-1ace-4077-ac8e-4203f602c967.png">
<img width="588" alt="Screenshot 2022-06-29 at 14 45 16" src="https://user-images.githubusercontent.com/986903/176451979-6bbbf335-ca51-4917-9c89-00da707d0c18.png">

I was repeatedly exiting the room and re-entering on the other client, so this is probably some kind of race where the metadata hasn't arrived fast enough?

**Comment by SimonBrandner** [comment]
I've seen something similar a long time ago (probably a different bug); it was caused by the other side using a wrong `streamId` in the metadata - it would be good to check what the metadata actually is

**Comment by dbkr** [comment]
I haven't seen this in recent memory: closing.
