### ISSUE TITLE
The app never waits for to-device events to be decrypted

### ISSUE THREAD

**Issue by robintown** [vector-im/element-call#428]
https://github.com/matrix-org/matrix-js-sdk/blob/robertlong/group-call/src/webrtc/callEventHandler.ts#L143

The above doesn't seem to be accomplishing anything, and is a possible source of signaling failures / splitbrains.

**Comment by dbkr** [comment]
I did wonder about this code as it didn't appear to be doing anything, although we do wait for everything to be decrypted in https://github.com/matrix-org/matrix-js-sdk/blob/robertlong/group-call/src/webrtc/callEventHandler.ts#L90

**Comment by robintown** [comment]
seems clear that I was wrong
