### ISSUE TITLE
Walkie talkie button does not work on mobile

### ISSUE THREAD

**Issue by foxlet** [vector-im/element-call#439]
### Steps to reproduce

1. Start a walkie-talkie call with 2 people
2. Press and hold on the button
3. Nothing happens (button does not light up)

#### What did you expect?
For it to show activity and sound for others in the same call.

#### What happened instead?
The button doesn't light up, although tapping it sometimes makes a beep heard by other users.

### Operating system

iOS

### Browser information

Safari 15

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by robintown** [comment]
Confirmed on Firefox for Android as well
