### ISSUE TITLE
Missing participant for one or more users due to e2e key changing ("splitbrain")

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#464]
### Steps to reproduce

This is a bug we're seeing where one or more users don't manage to connect to and receive media from one or more other users, while others in the conference can connect to them fine. Sometimes referred to as a splitbrain (although it's not really a true splitbrain: the room hasn't split into two separate rooms, it's just some people can't see others).

Appears to be due to keys changing:

```
2022-07-13T10:03:28.944Z W Ed25519 key for device [@amethyst-raw-ostrich:call.ems.host](https://matrix.to/#/@amethyst-raw-ostrich:call.ems.host):CNNZXXDWDZ has changed
```

### Will you send logs?

No

**Comment by ara4n** [comment]
i don't understand why other users don't melt at the key change though - only one in 6 users being impacted by a key change feels super weird.

**Comment by dbkr** [comment]
I couldn't see any obvious reason in the login / registration flows that the crypto store would be re-initialised, so I'm going to fix this in the simplest way by applying the same logic we use in Element of refusing to restore a session if we can't also recover the crypto data.

Unfortunately there's no way for a user to know if they previously had a different key, so we're going to have to force-logout everyone in a new version.
