### ISSUE TITLE
Joining a room that doesn't contain a group call hits timeout error

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#474]
### Steps to reproduce

If you try to join a room that doesn't have an ongoing group call, EC will sit there for a bit and then eventually show a timeout error. This could be because you created the room in a different client (unlikely on EC since it has its own dedicated homeserver) or possibly that the client failed / was closed whilst creating the room, or otherwise failed to send the state event to create the call.

We could perhaps just automatically start a group call if we don't find a group call in it, or we could prompt, although it would be hard to find sensible wording for a prompt that covers both those cases (we also might not have permission to start a group call, in the general case).

Another thing we could do is add the group call state event to `initialState` in the createRoom call which would make the whole operation atomic, meaning the second case wouldn't happen.

### Will you send logs?

No

**Comment by robintown** [comment]
> We could perhaps just automatically start a group call if we don't find a group call in it

This is what happens now, as of https://github.com/vector-im/element-call/pull/471

**Comment by dbkr** [comment]
Ah, I failed to read the resolution of the bug properly - thanks for doing that.
