### ISSUE TITLE
Investigation: Multiple group calls can be created in glare-like scenario

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#506]
### Steps to reproduce

We seem to be able to end up with multiple group calls in the same room. In this case we saw, the room got created with a group call in February, and then on July 20th Matthew iphone joined and 4 hours later, created a second group call, before going silent.

So:

 1. There may be some bug in our create-call-if-none-already logic
 2. We should probably handle mutliple group calls in a room in *some* way, eg. always join the most recently added.
 3. We probably want to guard against this in general. In EC we could add the call to initial_state when creating the room, but this wouldn't help other applications - I've brought this up on the MSC:  https://github.com/matrix-org/matrix-spec-proposals/pull/3401/files#r711950320

### Will you send logs?

No

**Comment by dbkr** [comment]
Further investigation reveals that it was probably a bug between #471 and #479 (ie. now fixed) where we didn't wait for the Room event to arrive after trying to join and before creating a call, so we just need to deal with rooms that have been broken by this bug, ie. probably pick the most recent conf.

**Comment by fkwp** [comment]
Follow up ticket https://github.com/matrix-org/matrix-js-sdk/issues/2589
