### ISSUE TITLE
A 1:1 full-mesh call results in 3 peer connections (1 audio+video with the other party and 2 audio-only with ourselves)

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-call#507]
### Steps to reproduce

1. User A joins a call
2. User B joins a call
3. We view WebRTC internals 

#### What did you expect?

1 peer-connections

#### What happened instead?

1 audio+video with the other party and 2 audio-only with ourselves

<hr>

It has been speculated this is a spatial audio bug

### Operating system

Not relevant

### Browser information

Chrome

### URL for webapp

https://element-call.netlify.app/

### Will you send logs?

No

**Comment by robintown** [comment]
This is necessary for making AEC work with spatial audio on Chrome - see https://github.com/vector-im/element-call/issues/381 for details
