### ISSUE TITLE
PTT (Walkie-Talkie) selection is broken

### ISSUE THREAD

**Issue by DoM1niC** [vector-im/element-call#534]
### 1. Try to create a Walki Talki Room
![grafik](https://user-images.githubusercontent.com/1436958/185499498-b7ab4fe3-66d7-4aa1-bc7c-e5099947f655.png)
![grafik](https://user-images.githubusercontent.com/1436958/185499516-5ad849b0-9757-4e6c-80ad-056bc0814099.png)

#### What did you expect?
Create a Voice only Room
#### What happened instead?
normal Video Chat Room

### Operating system

Windows

### Browser information

Firefox

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by robintown** [comment]
Confirmed on both the latest release and develop
