### ISSUE TITLE
Typescript strict mode

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#558]
### Your use case

We should try to enable typescript's strict mode on the EC codebase ASAP before writing too much new code. We can copy element-web's new strict-mode CI check.

**Comment by SimonBrandner** [comment]
I think it might not work due to js-sdk not passing strict checks... Though I agree we should steal the EW CI at the very least

**Comment by robintown** [comment]
We may be able to use https://github.com/allegro/typescript-strict-plugin to make this less painful (and work around the js-sdk not being strict)

**Comment by dbkr** [comment]
Conclusion on looking at this is:

> Dave
so if we just installed the plugin, we'd get strict mode errors in the IDE but it would still compile fine?
Robin
yes actually
Dave
and then we can also turn off the IDE errors per-file by adding that comment

...so as far as I'm concerned this sounds ideal

**Comment by robintown** [comment]
Will create a PR, then
