### ISSUE TITLE
Avatars look broken on call.element.io

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element-call#565]
![2022-09-01_16-46](https://user-images.githubusercontent.com/25768714/187943760-971be474-94b6-432c-b0ce-53c1d84a1a62.png)

**Comment by SimonBrandner** [comment]
Seems to only appear on Chrome

**Comment by robintown** [comment]
Still can't reproduce it on Chrome :P

**Comment by SimonBrandner** [comment]
_Weird_

**Comment by SimonBrandner** [comment]
Can anyone else repro this? I am on Chrome 105.0.5195.52
