### ISSUE TITLE
Full-screen button on any video feed; not just screenshares

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-call#566]
#### What would you like to do?

I was excited to see https://github.com/vector-im/element-call/pull/502, and assumed i'd be able to use it to fullscreen video when in spotlight mode.  (e.g. when interviewing someone or in 1:1 calls, it'd be nice to be able to pin the largest possible image of the main party without wasting screen real-estate on a border).  However, it only seems to be hooked up for screenshares, which feels like an unnecessary and sad constraint.

#### Why would you like to do it?

To maximise screen real estate and resolution when talking to someone, and having the most immersive experience. Also for parity with Jitsi.

#### How would you like to achieve it?

Add the fullscreen button as an option to all feeds; not just screenshares.

**Comment by robintown** [comment]
Per the decision on https://github.com/vector-im/element-call/pull/715, we're going to keep fullscreen buttons limited to screenshare feeds, but we may still consider adding [controls to fullscreen the entire interface](https://github.com/vector-im/element-call/issues/273).
