### ISSUE TITLE
can't start element-call with nginx reverse proxy

### ISSUE THREAD

**Issue by alpha856** [vector-im/element-call#582]
### Steps to reproduce

Hello, I have installed Synapse on localhost and also want to setup element call. Synapse run on localhost:8008. dut to instruction, i have git pull matrix-js-sdk and element-call repo. all things done and start dev server on port 3000 for every interfaces. but i have 2 problems in this state :
1- when i browse IP:3000, only black page was shown. and fav icon and title "Matrix Video Chat" is shown.
2- when i use nginx reverse proxy with this config, page try try and try to loading. one time screen is shown for 0.5 second and then try again to reloading and try try try. nginx config is here : 

    location ~ ^(/) {

        proxy_pass http://localhost:3000;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;

    }

### Outcome

-

### Operating system

Debian 11

### Will you send logs?

No

**Comment by dbkr** [comment]
The dev server is for development only, so isn't designed for use behind a reverse proxy. This is more of a support request than an issue so I'm going to close this, but we (or someone) may be able to help in #webrtc:matrix.org.
