### ISSUE TITLE
Add built tarball as release asset

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#588]
#### What would you like to do?
Have a simple tarball of the built version of Element Call as a downloadable asset on our releases.

#### Why would you like to do it?
Many people won't want to build their own, and the only thing we offer other than the source right now is a docker image.

**Comment by dbkr** [comment]
Oh, we should remember to include instructions to route everything to index.html

**Comment by lxp** [comment]
Thank you, this seems to be fixed since v0.3.3
