### ISSUE TITLE
When screen sharing, scrolling up and down the participants of the call doesn't include my own video in the scrolling

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/element-call#606]
### Steps to reproduce

I'm on a call, someone is sharing their screen.
The participants are displyed as a list on the side
If I scroll the list up and down, all participants' videos scroll, but mine

Video available [here](https://drive.google.com/file/d/1gXc03NzSmT6zWof7FxAZHtWO_QYvz6Mw/view?usp=sharing )

#### What did you expect?
My video should scroll alongside the others

#### What happened instead?
The others' video scroll above mine

### Operating system

MacOS

### Browser information

Firefox 104.0.2 (64-bit)

### URL for webapp

https://call.element.io     Version: v0.2.13

### Will you send logs?

No

**Comment by robintown** [comment]
We've fixed this in https://github.com/vector-im/element-call/pull/595, and a release is going out shortly
