### ISSUE TITLE
Choose/Pin stream while in spotlight

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-call#613]
#### What would you like to do?
I would like to select the stream that's shown in spotlight.

#### Why would you like to do it?
When enabling spotlight, it automatically puts the current speaker in spotlight, however another stream might be the most interesting one to watch, while audio is in background.

#### How would you like to achieve it?
Drag and drop like in freedom layout.

**Comment by SimonBrandner** [comment]
You can alredy double click a feed in freedom layout to focus on it :)

**Comment by HarHarLinks** [comment]
In that case, that feature was not discoverable to me at all.

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/vector-im/element-call/issues/615

**Comment by HarHarLinks** [comment]
I don't understand that process of spinning out a new issue rather than amending the old one. On top closing as wontfix rather than fixed if your argument to close is that the feature already exists.
