### ISSUE TITLE
Freedom layout doesn't work on 1:1 calls

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-call#646]
### Steps to reproduce

 * 1:1 video call someone
 * Try to layout the video feeds side by side (e.g. to screenrecord an interview)
 * Get very frustrated that double-clicking on the feeds doesn't work and freedom layout is disabled

#### What did you expect?

double-clicking on feeds in freedom mode in 1:1 call should let you lay them out side by side and rearrange and manually zoom etc as normal.

#### What happened instead?

double-click is ignored; you are stuck with a small thumbnail you can move, but not resize or relayout.

### Operating system

macOS

### Browser information

Chrome

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by robintown** [comment]
Regressed by https://github.com/vector-im/element-call/pull/632
