### ISSUE TITLE
undefined is not a constructor (evaluating 'new Intl.Locale(n[0])')

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#677]
This is appearing in rageshakes, although I can't tell where it's coming from.

**Comment by robintown** [comment]
Looks like it's coming from i18next, because the reporter is on Safari 12 which doesn't support `Intl.Locale`. Also there are quite a few errors due to `Promise.allSettled` being missing in Safari 12. @dbkr Should we close this as an unsupported platform?

**Comment by robintown** [comment]
Closing as such
