### ISSUE TITLE
Camera light is on even when camera is off

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-call#684]
### Steps to reproduce

1. Join a call with camera off

#### What did you expect?
Laptop webcam light is off

#### What happened instead?
Laptop webcam light is on, making me feel like the video is being received by the webapp :(

### Browser information

Chromium 106.0.5249.119 (Official Build) Arch Linux (64-bit)

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
Duplicate of https://github.com/vector-im/element-call/issues/195

**Comment by robintown** [comment]
@SimonBrandner That issue is closed, though?

**Comment by SimonBrandner** [comment]
> @SimonBrandner That issue is closed, though?

It's closed because it's caused by an upstream Chromium issue, so there really isn't much we can do here
