### ISSUE TITLE
Fix config file in release build

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#718]
We need to sort out config files in the release version: the Docker image should ship with no config file (ie. use all the defaults) which probably means adding an exclusion for 'config.json' in the redirect. It should have a way to map one in and we need to map a production one in for our live deployment.

**Comment by YamatoRyou** [comment]
I tried deploying Element Call in Synapse's Docker to replace Jitsi Meet with an unofficial image, but it didn't seem to work. Accessing the instance from a browser didn't seem to point directly to my Synapse server (shown as `call.ems.host`).

**Comment by dbkr** [comment]
@YamatoRyou I don't think this issue is related to your problems: try #webrtc:matrix.org for support.

**Comment by dbkr** [comment]
Fixed partially by https://github.com/vector-im/element-call/pull/798 and in our production deployment config
