### ISSUE TITLE
Video/audio breaks after detaching a tab in Safari

### ISSUE THREAD

**Issue by alfogrillo** [vector-im/element-call#740]
### Steps to reproduce

1. Open Safari with two tabs. In one tab you open an element call meeting.
2. Detach the tab with the Element call from the original window to create a new Safari window

#### What did you expect?
The call to continue

#### What happened instead?
The call didn't work

### Operating system

macOS Ventura 13.0

### Browser information

Safari16.1

### Will you send logs?

No

**Comment by robintown** [comment]
This appears to break in the same way in Jitsi. Closing since this needs to be fixed upstream.
