### ISSUE TITLE
server 500 Internal Server Error

### ISSUE THREAD

**Issue by hooshmandafzar** [vector-im/element-call#750]
### Steps to reproduce

error 500 on chat link. when share chat link in browser get 500 error

### URL for webapp

https://call.hooshmandafzar.com/555555555555

### Will you send logs?

No

**Comment by robintown** [comment]
https://call.element.io/555555555555 works, so this does not appear to be a bug in Element Call. Please check your server logs, and use [#webrtc:matrix.org](https://matrix.to/#/#webrtc:matrix.org) for support requests.

Also, visiting https://call.hooshmandafzar.com/555555555555 seems to work fine on my end?
