### ISSUE TITLE
Cannot join an SPA call without video/webcam

### ISSUE THREAD

**Issue by fkwp** [vector-im/element-call#768]
### Steps to reproduce

1. Use a computer without webcam
2. https://call.element.io/the_call or the netlify build

#### What did you expect?
joining the group call

#### What happened instead?
error msg: could not start video source

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
I am confused - this seems to work just fine for me

**Comment by fkwp** [comment]
Also works on my side -> will close the ticket
