### ISSUE TITLE
Keyboard shortcuts are enabled when writing in the feedback box

### ISSUE THREAD

**Issue by babolivier** [vector-im/element-call#771]
### Steps to reproduce

1. Join a call
2. Click on "Submit feedback" in the "..." menu
3. Start typing several words separated by spaces

#### What did you expect?

Nothing happens on the call.

#### What happened instead?

My mic goes on and off as a result of #749 

### Operating system

Arch Linux

### Browser information

Firefox 107.0

### URL for webapp

Video room on develop.element.io

### Will you send logs?

Yes

**Comment by babolivier** [comment]
Not submitting in-app logs because I observed this while typing https://github.com/matrix-org/matrix-video-chat-rageshakes/issues/1686 and so I assume anything that can be observed is already included there.

**Comment by robintown** [comment]
https://github.com/vector-im/element-call/issues/757 related
