### ISSUE TITLE
Add automatic logout

### ISSUE THREAD

**Issue by MomentQYC** [vector-im/element-call#786]
#### What would you like to do?
It can automatically log out of your current account when logging out of Element Call in another Matrix client (e.g. Element) or if the session is invalidated for other reasons.

#### Why would you like to do it?
It is too tedious to log out by clearing cookies every time I encounter this situation.

#### How would you like to achieve it?
Automatic logout when logout is detected.

### Have you considered any alternatives?

Cumbersome manual operation.

**Comment by MomentQYC** [comment]
> I'm afraid I don't understand what's being suggested here. Could you explain the configuration you have in mind for this scenario?

For example, when I logout the Element-call's session in Element-web, I can see the logout information in Element-call's console, but Element-call still shows the current account profile and cannot logout.

**Comment by dbkr** [comment]
I think maybe what you're describing is https://github.com/vector-im/element-call/issues/676 ?

**Comment by MomentQYC** [comment]
> 我想也许你描述的是#676？

Yes

**Comment by dbkr** [comment]
Dup of #676 then
