### ISSUE TITLE
Keyboard Shortcuts no longer work on call.element.io/element-call.netlify.app

### ISSUE THREAD

**Issue by youmuichi** [vector-im/element-call#793]
### Steps to reproduce

1. Where are you starting? What can you see?
just the element call with everyone
2. What do you click?
m for mute, v for video, spacebar for pushtotalk
3. More steps…
thats really it

#### What did you expect?
m to toggle mute, v to toggle video, space to toggle pushtotalk (there may be more keybinds i am not aware of aswell)

#### What happened instead?
the keybinds seem to not function, v doesnt do anything, neither does m or space, 

### Browser information

i tried qutebrowser and firefox

### Will you send logs?

Yes

**Comment by SimonBrandner** [comment]
Keyboard shortcuts work for me on element-call.netlify.app and I don't think we ever had them on call.element.io since they got added after the last release (see https://github.com/vector-im/element-call/pull/749)

Are you sure this wasn't just a flake? :P

**Comment by youmuichi** [comment]
ill test on my laptop, gimme a few minutes :D

**Comment by youmuichi** [comment]
maybe i was thinking of jitsi? (i did use it for years before element call,)

**Comment by youmuichi** [comment]
yeah i was definitely thinking of jitsi, my bad haha, im happy keyboard shortcuts are being added though, i guess i can close this, thank you simon for your time and support

**Comment by youmuichi** [comment]
also they work on netlify now!!
