### ISSUE TITLE
Guillaume cannot hear me

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-call#795]
### Steps to reproduce

1. 1:1 call with Guillaume
2. Mic config looks good, shows audio send to the browser

#### What did you expect?

Guillaume can hear me

#### What happened instead?

He cannot

I am able to hear him

### Operating system

Ubuntu 22.04.1 LTS

### Browser information

Firefox 108.0.1 (64-bit)

### URL for webapp

https://call.element.io/

### Will you send logs?

Yes

**Comment by dbkr** [comment]
The hope is that these bugs will be resolved by https://github.com/vector-im/element-call/pull/791

**Comment by robintown** [comment]
Michael is using Firefox though, so it seems a little unlikely. @weeman1337 Do you have spatial audio enabled in settings?

**Comment by robintown** [comment]
Oh, I misread, actually what's important is what browser Gillaume was on, and whether he had spatial audio enabled. @giomfo?

**Comment by giomfo** [comment]
I was on Google Chrome Version 108.0.5359.124, I don't know about spatial audio config (it is in default mode)

**Comment by weeman1337** [comment]
This was before livekit → closing
