### ISSUE TITLE
NPE in SFU mode on hangup

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#830]
### Steps to reproduce

1. Enter call in SFU mode
2. Not sure (other participant hangs up, maybe?)

### Outcome

NPE on https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/webrtc/groupCall.ts#L1034 - Cannot read properties of null (reading 'userId') because invitee is the sfu, which is not in the room.

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/commit/378cf7922e6710c534315db25485eefb42625ab7
