### ISSUE TITLE
Releasing camera on video mute is unreliable

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#847]
### Steps to reproduce

1. Enter call
2. Mute video

#### What did you expect?
Camera light goes off

#### What happened instead?
Camera light stays on sometimes, although it does work other times. Haven't yet found a correlation - I'd assume we must have a stray stream kicking around. It still fails sometimes when I'm the the only person in the call.

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
I can't repro :/
