### ISSUE TITLE
Guests with element-call appear in search

### ISSUE THREAD

**Issue by BlackSazha** [vector-im/element-call#859]
### Your use case

Hello all!
After the guest joined from the video conference, he also began to appear in the element search
![2023-01-19_09-09-24](https://user-images.githubusercontent.com/35872063/213339140-d4ef6c99-ddc6-4fee-9732-43391536dead.png)
![2023-01-19_09-12-18](https://user-images.githubusercontent.com/35872063/213339431-7599e660-eff8-4947-b832-ea1162c131f2.png)
Is it possible to make sure that these users do not appear in the system?
PS: Sorry for my bad English

**Comment by robintown** [comment]
Thank you for your report. Currently, we expect Element Call to be backed by a dedicated homeserver, and as such, running both Element and Element Call off the same server is not a use case we support.
