### ISSUE TITLE
Error message that registration is disabled when trying to start a call as guest on self-hosted instance

### ISSUE THREAD

**Issue by dinosmm** [vector-im/element-call#881]
### Steps to reproduce

1. Where are you starting? What can you see?

Home page, I can see the fields for video call name and display name.

2. What do you click?

I type call and display names, then click on 'Go'.

I see the error message:

```
MatrixError: [403] Registration has been disabled (https://serifos.uk/_matrix/client/r0/register)
```

#### What did you expect?

I expected the call to be established, same as the behaviour of the instance on call.element.io.

#### What happened instead?

Got an error message that my homeserver has registrations disabled (which it has, according to best practice).

I tried setting my HS to enable registration with token, and/or with email only. The error message says "no authentication flow", which I assume means that Element Call can't handle that scenario.

I also tried to log in with my HS account but it just hangs at 'logging in'.

Is this a bug, a misconfiguration on my part, or does Element Call in its current state really not allow guest calls on HS without open registration?

I can submit logs; if you need them, please let me know where to obtain them as no obvious option exists in the UI.

### Operating system

Debian 11

### Browser information

Firefox 108.0.2

### URL for webapp

0.3.4

### Will you send logs?

Yes

**Comment by fw23git** [comment]
Same problem here.

**Comment by fkwp** [comment]
https://github.com/vector-im/element-call/issues/873
