### ISSUE TITLE
Firefox's resistFingerprinting appears to cause problems

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#886]
### Steps to reproduce

1. Join a call in Firefox with the resistFingerprinting flag enabled

#### What did you expect?
Possibly no video or audio capture possible if resistFingerprinting prevents getUserMedia entirely(?) but we should be able to see & hear everyone else.

#### What happened instead?
Reports of not being able to hear others in addition to the user not being able to see their own video.

### Will you send logs?

No

**Comment by robintown** [comment]
https://github.com/vector-im/element-call/issues/396 related
