### ISSUE TITLE
Pressing „m“ toggles mute everywhere

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-call#888]
### Steps to reproduce

It looks like „m“ toggles mute from everywhere.

1. Open settings or change your display name
2. Type „m“

#### What did you expect?

No mute toggle

In settings: nothing
While changing display name: Just type the „m“

#### What happened instead?

„m“ toggles mute

### Operating system

Ubuntu 22.04.1 LTS

### Browser information

Firefox 109.0.1

### URL for webapp

https://call.element.io/

### Will you send logs?

No

**Comment by robintown** [comment]
https://github.com/vector-im/element-call/issues/757 related
