### ISSUE TITLE
Allow Element Call to be started without audio / video interface for the sake of a screen-sharing only session

### ISSUE THREAD

**Issue by fkwp** [vector-im/element-call#902]

**Comment by EnricoSchw** [comment]
Changed `matrix-js-sdk` to enable feature changes in EC. When this PR is merged we can build PR for EC
https://github.com/matrix-org/matrix-js-sdk/pull/3162

**Comment by EnricoSchw** [comment]
For testing we need to enable the feature in the in `config.json` with:

```json
{
  ...
  "features": {
      "feature_group_calls_without_video_and_audio": true
    }
}
```
