### ISSUE TITLE
Other party can't see video once unmuted if you enter a call with video muted

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-call#925]
### Steps to reproduce

 1. Join call early with voice and video disabled
 1. The other party joins the call
 1. I unmute and enable video to start talking
 1. The other party can hear me but can't see my video. From their perspective, it appears as if I have not enabled video. 

Re-joining fixes the problem

---

Also discussed in an [internal room](https://matrix.to/#/!dXHEZfLxIQzAELxzQd:matrix.org/$jtr9R6DKtw5Rignxe_4cjfr6Bo8VcG4HWI8Paeeqm6M?via=matrix.org&via=element.io&via=one.ems.host)

#### What did you expect?

Voice and video is received by the other party

#### What happened instead?

The other person can hear me but not see my video.

---

Here are logs for 3 reproductions. This has been happening consistently for the past 3+ weeks:

**Call 2023-02-03 (`RVO1KGlKr8iGQYmB`):**

 - Eric side: https://github.com/matrix-org/matrix-video-chat-rageshakes/issues/2047
 - Neil side: https://github.com/matrix-org/matrix-video-chat-rageshakes/issues/2048

**Call 2023-02-09 (`trtLuSF5rj3FZ4jW`):**

 - Eric side: https://github.com/matrix-org/matrix-video-chat-rageshakes/issues/2096
 - Neil side: https://github.com/matrix-org/matrix-video-chat-rageshakes/issues/2097

**Call 2023-02-19 (`5eA0SNcZtEmLHmmy`):**

 - Eric side: https://github.com/matrix-org/matrix-video-chat-rageshakes/issues/2135
 - Neil side: https://github.com/matrix-org/matrix-video-chat-rageshakes/issues/2136

### Operating system

Looks like we're both using Macbooks with whatever latest version of Chrome (see logs)

### Browser information

Chrome (latest)

### URL for webapp

https://call.element.io/

### Will you send logs?

Yes

**Comment by dbkr** [comment]
Looks like your client is fairly convinced that the video stream is indeed muted, so must have somehow got out of sync with the UI?

**Comment by MadLittleMods** [comment]
> Looks like your client is fairly convinced that the video stream is indeed muted, so must have somehow got out of sync with the UI?

I'm not convinced exactly since I think it looks enabled on my side and I can for sure see my video going.

As a separate thing in any case, if we can't rely on the state of the app being reflected in the UI, then we should log various things when the debug log dialog is opened [like we do in Element for the timeline](https://github.com/matrix-org/matrix-react-sdk/pull/8502).

**Comment by dbkr** [comment]
Looks like the video was indeed quite happily playing in the background, behind the overlay, but the client thought that it was muted. As an extra bonus, you get a different failure mode depending on who calls who in the lowest-lexicographic-userid contest (it starts by negotiating audio only and then neither party can see each other after video unmute).

**Comment by robintown** [comment]
Releases are ad-hoc, but it takes some time for us to do QA on them, so we're probably going to wait to get a few other changes in before doing a release
