### ISSUE TITLE
Incorrectly claims camera/microphone permissions are missing

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-call#929]
### Steps to reproduce

1. Go to call, eg https://call.element.io/room/#test:call.ems.host

#### What did you expect?

Joined call

#### What happened instead?

![image](https://user-images.githubusercontent.com/1389908/220925022-71dd27d0-4565-403f-a687-fed256d18ddc.png)

But:

![image](https://user-images.githubusercontent.com/1389908/220925150-e1693887-4109-4c4c-846e-5e2298417fa1.png)

### Operating system

Ubuntu 22.04

### Browser information

Firefox 106.0.5

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by fkwp** [comment]
Do you know if there was another process running having exclusive access to your webcam?
