### ISSUE TITLE
Add opt in banner that asks the user to opt in (when starting the call or opening the app).

### ISSUE THREAD

**Issue by toger5** [vector-im/element-call#930]
https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/Element-Call?node-id=3078%3A66101&t=687YjXcBIvcxqnNJ-0
<img width="885" alt="Screenshot 2023-02-23 at 16 14 04" src="https://user-images.githubusercontent.com/16718859/220948253-177158d2-0e9e-46dc-8eb4-1e9bd02b5e29.png">
<img width="885" alt="Screenshot 2023-02-23 at 16 15 03" src="https://user-images.githubusercontent.com/16718859/220948257-9bc8a608-0aeb-4580-82e2-59d031918212.png">

**Comment by toger5** [comment]
Current solution:
<img width="782" alt="Screenshot 2023-02-28 at 18 35 11" src="https://user-images.githubusercontent.com/16718859/221933141-4bcd8c1b-0a75-45c5-8098-e3e036c23a66.png">
<img width="782" alt="Screenshot 2023-02-28 at 18 35 17" src="https://user-images.githubusercontent.com/16718859/221933320-6ce4212f-b193-4d88-a0c5-e3a0651a0d6f.png">
<img width="782" alt="Screenshot 2023-02-28 at 18 35 21" src="https://user-images.githubusercontent.com/16718859/221933372-9c16ebe8-57ee-4640-b456-3dac05a85b99.png">

**Comment by gaelledel** [comment]
All good thank you!
