### ISSUE TITLE
Settings improvements

### ISSUE THREAD

**Issue by gaelledel** [vector-im/element-call#945]
1. Currently in Element call, it is not possible to access the settings outside a call. We're therefore introducing two new access points:
- One from the home screen from the top right dropdown
- One from the lobby screen from the top right dropdown

2. On the Lobby and call screen, we need to tidy the call control bar. Currently we have a "..." more with  " Invite people" and "Submit feedback". These are now available in the settings pannel see : https://github.com/vector-im/element-call/issues/930
We can therefore:
- Remove “invite people” and  “Submit feedback”
- Change the icon to a cog wheel settings icon

3. Profile info and ability to change picture are moving inside the settings panel
- Remove the User avatar in the top nav and replace with Add people button
- Add a Profile Tab in the settings panel.

Please see the design specs here https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/Element-Call?node-id=2874%3A65659&t=4siROGzgsVJa3Twi-4

**Comment by gaelledel** [comment]
@toger5 You might be able to help?

**Comment by robintown** [comment]
To keep you up to date @gaelledel, we'll get this done as part of exiting the SPA from beta, but for now it's prioritized below our work to improve the app's stability.
