### ISSUE TITLE
Per-user volume sliders

### ISSUE THREAD

**Issue by grahhnt** [vector-im/element-call#968]
#### What would you like to do?
I would like the ability to change each participants' volume for me, similar to how Discord does it

#### Why would you like to do it?
If someone is a bit too loud for me, I would like to turn them down on my end

#### How would you like to achieve it?
Within Discord, right-clicking on a user in a call will bring up a volume slider. Something similar to that would be nice

### Have you considered any alternatives?

no

### Additional context

no

**Comment by robintown** [comment]
This feature is already available: https://github.com/vector-im/element-call/pull/493

**Comment by grahhnt** [comment]
It took me a bit to find that option, would it be possible to also have a context menu for when you right-click on someone? Or have it show that header when you try and right click?
