### ISSUE TITLE
How to disable 'collection of anonymous data' in config.json

### ISSUE THREAD

**Issue by rg-artcom** [vector-im/element-call#969]
### Your use case

I would like to disable the 'collection of anonymous data' and other anti-privacy functionality.
May be it's allready possible but I don't find the documentation to do these presets in config.json.

**Comment by rg-artcom** [comment]
May be like this?

export interface ConfigOptions {
  posthog?: {
    api_host: null;
  };
  sentry?: {
    DSN: null;
  };
  rageshake?: {
    submit_url: null;
  };
}

**Comment by robintown** [comment]
A config.json of `{ posthog: undefined, sentry: undefined }` will do that, yeah

**Comment by robintown** [comment]
Ah, well, actually, `undefined` isn't a valid keyword in JSON, so you should just leave out the `posthog` and `sentry` sections.

**Comment by rg-artcom** [comment]
If I leave anything out about posthog of config.json I still have this "By ticking this box you consent to the collection of anonymous data, .." Text on the home-page.
If the default (no posthog entry in config.json) is not to collect data there shouldn't be a text block like this.
I would like to have a configuration where the user does not need to think about 'collection of data'.

**Comment by robintown** [comment]
Thanks for pointing that out. I've updated https://github.com/vector-im/element-call/pull/958 so that the analytics checkbox isn't shown at all if the deployment does not support analytics, which should address your concern
