### ISSUE TITLE
Add support for WKWebView (iOS)

### ISSUE THREAD

**Issue by alariej** [vector-im/element-call#973]
#### What would you like to do?
Use ElementCall in Android and iOS apps.

#### Why would you like to do it?
Would be great to use ElementCall on mobile phones.

#### How would you like to achieve it?
Embed ElementCall in a react-native-webview component by using the matrix-widget-api.

### Have you considered any alternatives?

Not yet.

### Additional context

The Android WebView mostly works. There is one upstream bug (preview video freezes on some devices) that has been reported, but otherwise ElementCall is fully usable in the current state.

The iOS WebView however doesn't properly work. Here a few issues I have observed:
- The preview video is not showing until the audio has been muted, then unmuted.
- Video muting, then unmuting, results in a black screen (preview and in-call).
- Video tile of joining participant is sometimes wrongly placed (upper left corner).
- Video tile of joining participant sometimes shows a black screen.
- Video of joining participant is sometimes zoomed in.

To make things worse, there seems to be differences between iOS 15 and iOS 16, the later having the issues more frequently.

**Comment by alariej** [comment]
Just found the issue with WKWebView. Nothing to do with ElementCall, but rather with react-native-callkeep, which takes over the audio routing, leaving ElementCall hanging when attempting to play the video stream.

**Comment by fibernetics-bying** [comment]
Hi @alariej do you mind to provide some high level instructions about how to embed Element Call to mobile apps? I am new to Matrix.

**Comment by alariej** [comment]
Hi, Quadrix for mobiles is built on React Native, so it uses [react-native-webview](https://github.com/react-native-webview/react-native-webview) to show the Element Call web app (as if it was a normal web page). It is then integrated with the rest of Quadrix (so that API calls can be made to the user's Matrix homeserver) by using the [matrix-widget-api](https://github.com/matrix-org/matrix-widget-api). The Element Call code for all Quadrix platforms (Android, iOS and web) can be found  [here](https://github.com/alariej/quadrix/tree/dev/src/modules/ElementCall). I think this is the same concept used by the Element apps, but I'm not sure it their implementation has been officially released.

**Comment by fibernetics-bying** [comment]
@alariej thank you sir.
