### ISSUE TITLE
Measure if we have media for each m.call.members

### ISSUE THREAD

**Issue by fkwp** [vector-im/element-call#977]
Measure if we have media for each m.call.members (on each WebRTC stats event every 10 sec). Aggregate the information in such a way that we have a percentage of received media (on a 10 sec stats update basis)

**Comment by fkwp** [comment]
https://github.com/vector-im/voip-internal/issues/124

**Comment by EnricoSchw** [comment]
PR's:
[Matrix JS SDK](https://github.com/matrix-org/matrix-js-sdk/pull/3241)
[Element Call](https://github.com/vector-im/element-call/pull/974)

**Comment by EnricoSchw** [comment]
Indicator:

We have a new OTel Report inside the Stats span with the structure:

```json
{ 
    "receivedMedia": 1,
    "receivedAudioMedia": 0.75, 
    "receivedVideoMedia": 1 
}
```
It measures when we receive even the smallest byte. As soon as we receive only one audio byte or one video byte, it is considered that the media connection is established and for this participant the unit of 'receivedMedia' will set. (This explains the example value on top) The values are between 0 and 1.

**Comment by EnricoSchw** [comment]
Mute Video: If a participant mutes the video, then it also does not send any bytes.

Mute Audio: If a participant mutes the audio, then it still sends bytes that we receive. The value under 1Kbyte/s: 

Not Audio Muted:
![Bildschirmfoto 2023-04-03 um 14 41 36](https://user-images.githubusercontent.com/1362436/229518308-3e696217-20fd-430d-87b8-bbf2cba648ea.png)

Audio is Muted (both side):
![Bildschirmfoto 2023-04-03 um 14 42 11](https://user-images.githubusercontent.com/1362436/229518495-073c38b9-4924-4e5d-bd62-440019149335.png)

Chrome stats:
![Bildschirmfoto 2023-04-03 um 14 43 24](https://user-images.githubusercontent.com/1362436/229518757-79af48f2-9736-4f6d-843f-e98e8ad3f9ec.png)

**Comment by EnricoSchw** [comment]
I think bytes received its not a real indication if a media pipeline was initialized.
The following criteria are necessary for a media pipeline:
1. A tack has been negotiated and the correlating Transceiver is receiving (`RTCRtpTransceive.currentDirection = sendrecv  | recvonly `)
2. The remote track on the Receiver is live! (`MediaStreamTrack.readyState = live`)
3. The signal status of the RTC connection is stable (`RTCPeerConnection.signalingState=stable`)

Dependens how we have mute implemented (`MediaStreamTrack.enable` or `MediaStreamTrack.muted` )
With these criteria, could we provide a relatively accurate picture of whether Mediastream pipelines could be initialized.

**Comment by EnricoSchw** [comment]
## Summary stand up: 4/3/23

### Conclusion: 

We don't want to measure whether a media pipeline is possible. We want to measure whether we receive media.

### Case Audio
Because in case of audio, we also receive bytes if peer muted audio, so we can leave the statistics as they are.

### Case Video
Wir möchten den fall ausschließen dass der Peer video muted. If the video is muted we don't get any bytes. Therefore we check the mute state of a track and treat it as if we received bytes.

**Comment by EnricoSchw** [comment]
## Description of the calculation:
### Audio
The calculation for received audio media data remains. Once we receive only one audio byte. The value is measured for the call as Media Connected. 

### Video
Once we receive only one video byte, then the same like audio.
In case we don't receive a video byte, we check if **ALL** tracks are muted 

### Source Code (The Main important Changes)
The for the Stats you will find in the [`build`](https://github.com/matrix-org/matrix-js-sdk/blob/fb8a8a29b2a7a67f280863da26b9eea439fa4d82/src/webrtc/stats/summaryStatsReporter.ts#L20) methode of the `SummaryStatsReporter`.

For Track muted condition, please check [`setTrackAliveState`](https://github.com/matrix-org/matrix-js-sdk/blob/fb8a8a29b2a7a67f280863da26b9eea439fa4d82/src/webrtc/stats/trackStatsReporter.ts#L118)  method of the `TrackStatsReporter`. Here I set `isAlive' Property for remote Tracks as indicator Track is not muted.
