### ISSUE TITLE
"JavaScript heap out of memory" in the build process

### ISSUE THREAD

**Issue by MomentQYC** [vector-im/element-call#978]
### Steps to reproduce

1. run `yarn` and `yarn build`
2. The error occurs and the process is interrupted.

#### What did you expect?
Successfully build
#### What happened instead?
```shell
<--- Last few GCs --->

[1995771:0x66ed170]    96045 ms: Scavenge (reduce) 2042.8 (2081.6) -> 2042.6 (2082.3) MB, 14.8 / 0.0 ms  (average mu = 0.475, current mu = 0.384) allocation failure; 
[1995771:0x66ed170]    98419 ms: Mark-sweep (reduce) 2043.6 (2082.3) -> 2043.2 (2082.8) MB, 2372.4 / 0.0 ms  (average mu = 0.270, current mu = 0.019) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb7b3f0 node::Abort() [node]
 2: 0xa8c89a  [node]
 3: 0xd631b0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xd63557 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xf40c55  [node]
 6: 0xf5313d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: 0xf2d83e v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 8: 0xf2ec07 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 9: 0xf0fdda v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
10: 0x12d36cf v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x1700579  [node]
Aborted
```
Node.js v18.14.2
This problem is recent and there was no problem before.

### Operating system

Ubuntu 20.04

### Will you send logs?

No

**Comment by dbkr** [comment]
https://github.com/vector-im/element-call/commit/d53be695f906615b7a49893e1d102aa5199fa5ac fixes this on the github actions workflow, but this can still be a problem in general.

https://github.com/vitejs/vite/issues/2433 to link to the parent bug in Vite.

**Comment by MomentQYC** [comment]
> https://github.com/vector-im/element-call/commit/d53be695f906615b7a49893e1d102aa5199fa5ac fixes this on the github actions workflow, but this can still be a problem in general.
> 
> 
> 
> https://github.com/vitejs/vite/issues/2433 to link to the parent bug in Vite.

There is a very high probability that this issue will be triggered during the user's own build process, so I think it is necessary to modify the package.json
